### ISSUE TITLE
[Egg Request]: Conan Exiles

### ISSUE THREAD

**Issue by GMalvestiti** [QuintenQVD0/Q_eggs#102]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/440900/Conan_Exiles/

### Links for the download

https://store.steampowered.com/app/440900/Conan_Exiles/

### Links for the install docs

https://www.conanexiles.com/dedicated-servers/

### Does this app work on ARM?

No

**Comment by QuintenQVD0** [comment]
I tryed but it seems like it does not work, if you want to try for yourself:

[egg-conan-exiles.json](https://github.com/QuintenQVD0/Q_eggs/files/14921322/egg-conan-exiles.json)
