### ISSUE TITLE
[Egg Request]: ARK: Survival Evolved

### ISSUE THREAD

**Issue by Rmlyy** [QuintenQVD0/Q_eggs#11]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/346110/ARK_Survival_Evolved/

### Links for the download

https://ark.fandom.com/wiki/Dedicated_server_setup

### Links for the install docs

https://ark.fandom.com/wiki/Dedicated_server_setup

### Does this app work on ARM?

I don't know

**Comment by kry008** [comment]
https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/ark_survival_evolved

**Comment by Rmlyy** [comment]
> https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/ark_survival_evolved

Doesn't work: ```exec /bin/bash: exec format error```

**Comment by kry008** [comment]
This is steam game, and on ARM will not work

**Comment by QuintenQVD0** [comment]
I will have a look but 99.9% it will not work.

**Comment by QuintenQVD0** [comment]
I can never get this to work as the source docker image includes lib32gcc-s1 what is needed for steam games and is nat availble on arm

**Comment by QuintenQVD0** [comment]
@Rmlyy If your still intrested run 

```sh
curl -sSL https://raw.githubusercontent.com/QuintenQVD0/Q_eggs/steamcmd/steamgames.sh | bash
``` 

**on the host os**!
it will take some time

If it is done send me the output of
`box64 --version`
`box86 --version`

I have a working egg but my pi has not enough ram to 100% start the server

**Comment by Rmlyy** [comment]
@QuintenQVD0 hi, here is the output:

```
root@arm2:/home/darius# box64 --version
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Cores:4
Box64 with Dynarec v0.2.0 66686141 built on Nov 21 2022 10:20:29
root@arm2:/home/darius# box86 --version
Box86 with Dynarec v0.2.8 891593c1 built on Nov 21 2022 10:17:45
root@arm2:/home/darius#
```

Ran on an Oracle 4 Core 24 GB RAM free instance.

**Comment by QuintenQVD0** [comment]
> @QuintenQVD0 hi, here is the output:
> 
> ```
> root@arm2:/home/darius# box64 --version
> Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Cores:4
> Box64 with Dynarec v0.2.0 66686141 built on Nov 21 2022 10:20:29
> root@arm2:/home/darius# box86 --version
> Box86 with Dynarec v0.2.8 891593c1 built on Nov 21 2022 10:17:45
> root@arm2:/home/darius#
> ```
> 
> Ran on an Oracle 4 Core 24 GB RAM free instance.
> 
> Edit: By the way, the link given by you in the previous comment returns 404 not found, so I've copied the link from the README file.

Yea the branch got merged

**Comment by QuintenQVD0** [comment]
here ^^ so now you can test it and let me know if it works
