### ISSUE TITLE
[Egg Request]: V Rising Arm Server

### ISSUE THREAD

**Issue by davidjaraba** [QuintenQVD0/Q_eggs#113]
### Does this expand an already existing service

Yes

### Link to a game or software

https://store.steampowered.com/app/1604030/V_Rising/

### Links for the download

https://store.steampowered.com/app/1604030/V_Rising/

### Links for the install docs

https://www.rockpapershotgun.com/v-rising-server

### Does this app work on ARM?

Yes

**Comment by QuintenQVD0** [comment]
We can not run wine under an emumlator only proton and we need wine with winetricks so this is not possible
