### ISSUE TITLE
[Bug]: FiveM Arm64 resource bug

### ISSUE THREAD

**Issue by Alvv2115** [QuintenQVD0/Q_eggs#115]
### Panel Version

1.11.7

### Wings Version

 1.11.13

### Service

fivem arm

### Modified

No, I did not modify the egg

### Expected Behavior

my txadmin console does not see any resources (except the default ones) or load them, but they are in the files
![image](https://github.com/QuintenQVD0/Q_eggs/assets/112778107/6f37844a-a9a5-4194-9ed1-9e1f11bb6759)
![image](https://github.com/QuintenQVD0/Q_eggs/assets/112778107/181c41df-8393-4ac5-bb9f-099c5b629634)

### Actual Behavior

my server doesn't see any additional resources and I don't know how to fix it

### Steps To Reproduce

setup txadmin
install extra resources (like script)

### Install logs

cd /home/container/fivem; export HOME=/home/container; FEXInterpreter /home/container/fivem/alpine/opt/cfx-server/ld-musl-x86_64.so.1 --library-path "/home/container/fivem/alpine/usr/lib/v8/:/home/container/fivem/alpine/lib/:/home/container/fivem/alpine/usr/lib/" -- /home/container/fivem/alpine/opt/cfx-server/FXServer +set citizen_dir /home/container/fivem/alpine/opt/cfx-server/citizen/ +set sv_licenseKey ${FIVEM_LICENSE} +set steam_webApiKey ${STEAM_WEBAPIKEY} +set sv_maxplayers ${MAX_PLAYERS} +set serverProfile default +set txAdminPort ${TXADMIN_PORT} $( [ "$TXADMIN_ENABLE" == "1" ] || printf %s '+exec server.cfg' )

**Comment by Alvv2115** [comment]
and it dont see any .cfg files

**Comment by QuintenQVD0** [comment]
No install logsis notthing I can do. And that resourcrs bug is and always will be their. Thats their also on amd64
