### ISSUE TITLE
[Bug]: FiveM Server Not Starting anymore

### ISSUE THREAD

**Issue by TheBeast737** [QuintenQVD0/Q_eggs#117]
### Panel Version

1.11.7

### Wings Version

1.11.13

### Service

FiveM Arm64 Version

### Modified

No, I did not modify the egg

### Expected Behavior

The Server Starts Normal

### Actual Behavior

After i restarted the server it didn't start again i changed nothing in the settings or updated anything the server just crashes with this error: 
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from quintenqvd/pterodactyl_images 
Status: Image is up to date for quintenqvd/pterodactyl_images:dev_fex 
Digest: sha256:eb8b2835166984f52fda5023d69a23a18c7465c52cb30103c52d9a4961bd6ce4 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ cd /home/container/fivem; export FEX_APP_DATA_LOCATION=/home/container/rootfs/; export FEX_APP_CONFIG_LOCATION=/home/container/; export XDG_DATA_HOME=/home/container; FEXInterpreter /home/container/fivem/alpine/opt/cfx-server/ld-musl-x86_64.so.1 --library-path "/home/container/fivem/alpine/usr/lib/v8/:/home/container/fivem/alpine/lib/:/home/container/fivem/alpine/usr/lib/" -- /home/container/fivem/alpine/opt/cfx-server/FXServer +set citizen_dir /home/container/fivem/alpine/opt/cfx-server/citizen/ +set sv_licenseKey ${FIVEM_LICENSE} +set steam_webApiKey ${STEAM_WEBAPIKEY} +set sv_maxplayers ${MAX_PLAYERS} +set serverProfile default +set txAdminPort ${TXADMIN_PORT} $( [ "$TXADMIN_ENABLE" == "1" ] || printf %s '+exec server.cfg' )
Setting Default RootFS PATH
RootFS already downloaded
Needed config file exists, skipping
steam user is not set.
Using anonymous user.
No appid set. Starting Server
/entrypoint.sh: line 82:    15 Segmentation fault      (core dumped) FEXInterpreter /home/container/fivem/alpine/opt/cfx-server/ld-musl-x86_64.so.1 --library-path "/home/container/fivem/alpine/usr/lib/v8/:/home/container/fivem/alpine/lib/:/home/container/fivem/alpine/usr/lib/" -- /home/container/fivem/alpine/opt/cfx-server/FXServer +set citizen_dir /home/container/fivem/alpine/opt/cfx-server/citizen/ +set sv_licenseKey ${FIVEM_LICENSE} +set steam_webApiKey ${STEAM_WEBAPIKEY} +set sv_maxplayers ${MAX_PLAYERS} +set serverProfile default +set txAdminPort ${TXADMIN_PORT} $( [ "$TXADMIN_ENABLE" == "1" ] || printf %s '+exec server.cfg' )
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 139
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

![Capture](https://github.com/QuintenQVD0/Q_eggs/assets/85925669/ff2c5b0a-93d7-45e5-887d-968117608df1)

### Steps To Reproduce

Create a FiveM with the egg then start the Server

### Install logs

https://pteropaste.com/se2i

**Comment by davidjaraba** [comment]
Same problem and I didn´t edit any.

**Comment by QuintenQVD0** [comment]
YesI know. I will look in to it.

**Comment by Alvv2115** [comment]
> YesI know. I will look in to it.

how long to repair?

**Comment by QuintenQVD0** [comment]
> > YesI know. I will look in to it.
> 
> how long to repair?

I have vacation so some time.

**Comment by TheBeast737** [comment]
I got the issue fixed for me. All I did was restart my server where Pterodactyl is installed. After that, my Fivem server just started normally.
