### ISSUE TITLE
[Bug]: Crash on player join palworld

### ISSUE THREAD

**Issue by abo3skr2019** [QuintenQVD0/Q_eggs#118]
### Panel Version

1.11.7

### Wings Version

1.11.13

### Service

palworld

### Modified

No, I did not modify the egg

### Expected Behavior

install the server
start the server
enter server
play

### Actual Behavior

server crashes with this in the console
[Crashonjoinconsole.log](https://github.com/user-attachments/files/16133567/Crashonjoinconsole.log)

### Steps To Reproduce

arm64 4 core
20GB of ram
download the egg
create a server
run the install script
start the server
join server

### Install logs

https://pteropaste.com/sq51/

**Comment by QuintenQVD0** [comment]
I'm on vacation until the 16 so after that I can have a look.

**Comment by QuintenQVD0** [comment]
This should been fixt with an image update I pushed.
