### ISSUE TITLE
[Egg Request]: Euro Truck Simulator 2

### ISSUE THREAD

**Issue by Gahtee** [QuintenQVD0/Q_eggs#119]
### Does this expand an already existing service

Yes

### Link to a game or software

https://store.steampowered.com/app/227300/Euro_Truck_Simulator_2/

### Links for the download

https://github.com/pelican-eggs/eggs/tree/master/game_eggs/steamcmd_servers/truck-simulator/euro-truck-simulator2

### Links for the install docs

https://modding.scssoft.com/wiki/Documentation/Tools/Dedicated_Server

### Does this app work on ARM?

No

**Comment by QuintenQVD0** [comment]
Same as ats:

https://github.com/QuintenQVD0/Q_eggs/issues/89
