### ISSUE TITLE
[Egg Request]: SA-MP

### ISSUE THREAD

**Issue by redhyper9** [QuintenQVD0/Q_eggs#12]
### Does this expand an already existing service

No

### Link to a game or software

https://www.sa-mp.com/

### Links for the download

http://files.sa-mp.com/samp037svr_R2-1.tar.gz

### Links for the install docs

https://team.sa-mp.com/wiki/Linux_Server.html

### Does this app work on ARM?

No

**Comment by QuintenQVD0** [comment]
This is gone be dificult as the binary is 32 bit and not 64. I can try but it will take time

**Comment by QuintenQVD0** [comment]
This will curently not work as it is a 32 bit binary and the emulator for that can not be used in a docker image

**Comment by QuintenQVD0** [comment]
someone told me a trick on how to install box86 in a docker image, maby soon!

**Comment by Ashu11-A** [comment]
👀

**Comment by Rmlyy** [comment]
👀

**Comment by QuintenQVD0** [comment]
@Ashu11-A @redhyper9 Can someone test the egg from this PR: https://github.com/QuintenQVD0/Q_eggs/pull/13 I currently have no time for that

**Comment by Ashu11-A** [comment]
![Screenshot_20220815-104333_Chrome_1](https://user-images.githubusercontent.com/30575805/184657318-9636e813-4dfe-4640-9bd3-a1fbbf739f46.png)
![Screenshot_20220815-104222_Chrome_1](https://user-images.githubusercontent.com/30575805/184657323-88fc2481-86a0-4869-b014-a5ae35914ec5.png)
Nenhum funcionou

**Comment by Rmlyy** [comment]
Haven't tested yet but it will not work on ARM64 because box86 works only on ARM 32-bit.

**Comment by Ashu11-A** [comment]
@Rmlyy I made an egg with box86 and it worked perfectly on arm64

**Comment by QuintenQVD0** [comment]
> ade an egg with box86 and it worked perfectly on

I wonder wy, it is litery the same image

**Comment by QuintenQVD0** [comment]
As you see I got it to work, It is added to the repo!
