### ISSUE TITLE
[Egg Request]: Path of Titans

### ISSUE THREAD

**Issue by felipe-negri** [QuintenQVD0/Q_eggs#122]
### Does this expand an already existing service

No

### Link to a game or software

https://alderongames.com/

### Links for the download

https://alderongames.com/store/path-of-titans

### Links for the install docs

https://alderongames.com/pot-server-hosting

### Does this app work on ARM?

I don't know

**Comment by felipe-negri** [comment]
> that egg needs you to own the game so I can not test this, I can try to make it work but someone else must be active to test it

i can test

**Comment by felipe-negri** [comment]
Currently on an x86 server, I use this egg.json.
[pot.json](https://gist.github.com/felipe-negri/fb5bbe50db86b0f75f4662be73c6f69a)

**Comment by felipe-negri** [comment]
I managed to get the server running natively on arm64. Can I open the PR?

**Comment by QuintenQVD0** [comment]
Yes

**Comment by QuintenQVD0** [comment]
closed as of #123
