### ISSUE TITLE
[Egg Request]: Redm

### ISSUE THREAD

**Issue by MellowB1** [QuintenQVD0/Q_eggs#124]
### Does this expand an already existing service

Yes

### Link to a game or software

https://redm.net/

### Links for the download

https://redm.net/

### Links for the install docs

https://docs.fivem.net/docs/

### Does this app work on ARM?

I don't know

**Comment by QuintenQVD0** [comment]
currently with the state of the fivem egg (how unstable it is) I am going to say no to this, feel free to modify it and try it yourself
