### ISSUE TITLE
[Question] Satisfactory

### ISSUE THREAD

**Issue by calebroelens-somko** [QuintenQVD0/Q_eggs#125]
Sorry if this is not the right place for questions.

I'm looking into creating a Satisfactory server on a Oracle Cloud ARM based VM.

Most versions I have tested (Fexemu based images)the server crashes when placing belts. Does your version not have any issues with this?

Just asking before I attempt to install the panel and have to buy a FQDN.

Thanks.

**Comment by QuintenQVD0** [comment]
Is there a translator in place?

Else it works just fine for me any many others. Keep in mind this egg does not yet work with the 1.0 version of this game

**Comment by calebroelens-somko** [comment]
Thx for the answer. Was looking for a 1.0.

Ill probably end up trying some of the parameters you use in your docker images and egg and combine it with 
https://github.com/sa-shiro/Satisfactory-Dedicated-Server-ARM64-Docker

That way I van avoid the while setup with pterodactl.

Thanks.
