### ISSUE TITLE
[Bug]: HLDS Egg cannot execute binary file: Exec format error (SteamCMD)

### ISSUE THREAD

**Issue by Ketam1ne** [QuintenQVD0/Q_eggs#126]
### Panel Version

1.11.7

### Wings Version

1.11.13

### Service

HLDS/CS1.6

### Modified

No, I did not modify the egg

### Expected Behavior

I tried to install Counter-Strike but it doesnt work, it always shows this error its below "Actual Behavior"
I have ARM64 

### Actual Behavior

container@nookure~  Server marked as offline...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@nookure~  Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from quintenqvd/pterodactyl_images 
Status: Image is up to date for quintenqvd/pterodactyl_images:emulation 
Digest: sha256:06b46c33eee732c8a51beb9995a2be16027bbd459ba3e18064fef560febef998 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ AMD64 Emualtor image
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 PageSize:4096 Running on Neoverse-N1 with 4 Cores
Will use Hardware counter measured at 25.0 MHz emulating 3.2 GHz
Params database has 90 entries
Box64 with Dynarec v0.3.1 9fa43f23 built on Sep 15 2024 06:35:56
Box86 with Dynarec v0.3.7 f97763ca built on Sep 14 2024 06:20:08
user set to anonymous
./steamcmd/steamcmd.sh: line 37: /home/container/steamcmd/linux32/steamcmd: cannot execute binary file: Exec format error
:/home/container$ box86 ./hlds_run -console -game ${HLDS_GAME} -port ${SERVER_PORT} -sport ${VAC_PORT} +map ${SRCDS_MAP} +ip 0.0.0.0 -strictportbind -norestart
Box86 with Dynarec v0.3.7 f97763ca built on Sep 14 2024 06:20:08
Error: file is not found (check BOX86_PATH)

### Steps To Reproduce

./steamcmd/steamcmd.sh: line 37: /home/container/steamcmd/linux32/steamcmd: cannot execute binary file: Exec format error

### Install logs

root@instance-20221105-0851:/home/ubuntu# tail -n 1000 $(ls -Alrt /var/log/pterodactyl/install/.log | tail -1 | sed 's// /g' | cut -s -d' ' -f9) | nc pteropaste.com 99 ls: cannot access '/var/log/pterodactyl/install/.log': No such file or directory

**Comment by QuintenQVD0** [comment]
Seems like you did not ran the steamcmd script.

**Comment by Ketam1ne** [comment]
But what kind of script should i use? Because i use your egg to download HLDS Game but every time i press start it gives me this error code that i typed in topic

**Comment by QuintenQVD0** [comment]
> But what kind of script should i use? Because i use your egg to download HLDS Game but every time i press start it gives me this error code that i typed in topic

the steamcmd one mentioned in the readme

**Comment by QuintenQVD0** [comment]
This is an issue as the steamcmd script faild or was not ran
