### ISSUE TITLE
[Bug]: Satisfactory max Uobject reached / Memory building up and crash

### ISSUE THREAD

**Issue by PoprostuIzI** [QuintenQVD0/Q_eggs#128]
### Panel Version

1.11.5

### Wings Version

1.11.7

### Service

Satisfactory

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, mount the FEX, start and play

### Actual Behavior

Server crashed when trying to place miner mk1 with error 

`Fatal error: [File:.\Runtime/CoreUObject/Private/UObject/UObjectArray.cpp] [Line: 534] 
Maximum number of UObjects (2162688) exceeded when trying to add 1 object(s), make sure you update MaxObjectsInGame/MaxObjectsInEditor/MaxObjectsInProgram in project settings.
[2024.10.12-16.42.37:347][ 55]LogCore: Error: appError called: Fatal error: [File:.\Runtime/CoreUObject/Private/UObject/UObjectArray.cpp] [Line: 534] 
Maximum number of UObjects (2162688) exceeded when trying to add 1 object(s), make sure you update MaxObjectsInGame/MaxObjectsInEditor/MaxObjectsInProgram in project settings.
0x00007fffe1b128e8 libFactoryServer-CoreUObject-Linux-Shipping.so!FUObjectArray::AllocateUObjectIndex(UObjectBase*, EInternalObjectFlags, int, int) [C:/BuildAgent/work/b731a33f2a691e17/UE4/Engine/Source/./Runtime/CoreUObject/Private/UObject/UObjectArray.cpp:228]
0x00007fffe1b2bb8c libFactoryServer-CoreUObject-Linux-Shipping.so!UObjectBase::AddObject(FName, EInternalObjectFlags, int, int) [C:/BuildAgent/work/b731a33f2a691e17/UE4/Engine/Source/./Runtime/CoreUObject/Private/UObject/UObjectBase.cpp:221]
0x00007fffe1b3de1e libFactoryServer-CoreUObject-Linux-Shipping.so!StaticAllocateObject(UClass const*, UObject*, FName, EObjectFlags, EInternalObjectFlags, bool, bool*, UPackage*) [C:/BuildAgent/work/b731a33f2a691e17/UE4/Engine/Source/./Runtime/CoreUObject/Private/UObject/UObjectGlobals.cpp:3478]
0x00007fffe1b3cbf9 libFactoryServer-CoreUObject-Linux-Shipping.so!StaticConstructObject_Internal(FStaticConstructObjectParameters const&) [C:/BuildAgent/work/b731a33f2a691e17/UE4/Engine/Source/./Runtime/CoreUObject/Private/UObject/UObjectGlobals.cpp:4383]
0x00007ffe358bcbc5 libFactoryServer-FactoryGame-Linux-Shipping.so!AFGConveyorBeltHologram::UpdateSplineComponent() [C:/BuildAgent/work/b731a33f2a691e17/UE4/Engine/Source/./../../FactoryGame/Source/FactoryGame/Private/Hologram/FGConveyorBeltHologram.cpp:1430]
0x00007ffe358b7489 libFactoryServer-FactoryGame-Linux-Shipping.so!AFGConveyorBeltHologram::OnRep_SplineData() [C:/BuildAgent/work/b731a33f2a691e17/UE4/Engine/Source/./../../FactoryGame/Source/FactoryGame/Private/Hologram/FGConveyorBeltHologram.cpp:390]
0x00007ffe358b5c96 libFactoryServer-FactoryGame-Linux-Shipping.so!AFGConveyorBeltHologram::BeginPlay() [C:/BuildAgent/work/b731a33f2a691e17/UE4/Engine/Source/./../../FactoryGame/Source/FactoryGame/Private/Hologram/FGConveyorBeltHologram.cpp:58]
0x00007fffdfa8017c libFactoryServer-Engine-Linux-Shipping.so!AActor::DispatchBeginPlay(bool) [C:/BuildAgent/work/b731a33f2a691e17/UE4/Engine/Source/./Runtime/Engine/Private/Actor.cpp:4246]
0x00007fffdfa7faba libFactoryServer-Engine-Linux-Shipping.so!AActor::PostActorConstruction() [C:/BuildAgent/work/b731a33f2a691e17/UE4/Engine/Source/./Runtime/Engine/Private/Actor.cpp:4034]
0x00007fffdfa7245c libFactoryServer-Engine-Linux-Shipping.so!AActor::FinishSpawning(UE::Math::TTransform<double> const&, bool, FComponentInstanceDataCache const*, ESpawnActorScaleMethod) [C:/BuildAgent/work/b731a33f2a691e17/UE4/Engine/Source/./Runtime/Engine/Private/Actor.cpp:3932]
0x00007ffe358e0b59 libFactoryServer-FactoryGame-Linux-Shipping.so!AFGHologram::SpawnHologramFromRecipe(TSubclassOf<UFGRecipe>, AActor*, UE::Math::TVector<double>, APawn*) [C:/BuildAgent/work/b731a33f2a691e17/UE4/Engine/Source/./../../FactoryGame/Source/FactoryGame/Private/Hologram/FGHologram.cpp:167]
0x00007ffe3543952b libFactoryServer-FactoryGame-Linux-Shipping.so!UFGBuildGunStateBuild::InternalSpawnHologram() [C:/BuildAgent/work/b731a33f2a691e17/UE4/Engine/Source/./../../FactoryGame/Source/FactoryGame/Private/Equipment/FGBuildGunBuild.cpp:2066]`

After trying to set the uObject limit to a higher value

in `/home/container/FactoryGame/Saved/Config/LinuxServer/Engine.ini`
by:
`
[/script/engine.garbagecollectionsettings]
gc.MaxObjectsInEditor=100000000
gc.MaxObjectsInGame=100000000
`
Memory builds up to max and crash.

### Steps To Reproduce

Step 1: Create a new server with the specific instructions for Satisfactory for ARM Oracle with FEX
Step 2: Set version to experimental
Step 3: Set Ram to 12288
Step 4: Start the server
Step 5: Go to Satisfactory, add the server with correct ip and port
Step 5: Create a new game
Step 6: Join the game
Step 7: Find the nearest place where you can place the big Miner mk1 (not portable miner)
Step 8: Click 4 on your keyboard or whatever you have binded (conveyor belt on quick hotbar on the bottom of the screen)
Step 9: Look at the miner mk1 with the conveyor belt selected
Step 10: Crash `Maximum number of UObjects (2162688) exceeded when trying to add 1 object(s)` appears
Step 11: Forcefully stop the server
Step 12: Change the maximum number of objects inside `/home/container/FactoryGame/Saved/Config/LinuxServer/Engine.ini` by adding

[/script/engine.garbagecollectionsettings]
gc.MaxObjectsInEditor=100000000
gc.MaxObjectsInGame=100000000

to an empty space insife of that file

Step 13: Start the server
Step 14: Repeat steps 7-9
Step 15: Memory builds up to maximum and Out of Memory crash appears.

*INSTALL LOGS MAY NOT BE RIGHT, SATISFACTORY SERVER INSTALLED CORRECTLY.

### Install logs

https://ptero.co/uhepufebok

**Comment by QuintenQVD0** [comment]
This is a known issue see here: https://github.com/sa-shiro/Satisfactory-Dedicated-Server-ARM64-Docker?tab=readme-ov-file#-important-updated-for-10

**Comment by QuintenQVD0** [comment]
@PoprostuIzI This will be fixt with the next release
![afbeelding](https://github.com/user-attachments/assets/aaab992f-6563-4931-8dde-685d28f359c3)
