### ISSUE TITLE
[Egg Request]: Terraria tModLoader

### ISSUE THREAD

**Issue by raiancollyn** [QuintenQVD0/Q_eggs#130]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/1281930/tModLoader/

### Links for the download

https://store.steampowered.com/app/1281930/tModLoader/

### Links for the install docs

https://github.com/tModLoader/tModLoader/wiki/Starting-a-modded-server

### Does this app work on ARM?

I don't know

**Comment by QuintenQVD0** [comment]
No. This can not be done. It worked in the past but with some tmodloader update it all broke and can not be done anymore.
