### ISSUE TITLE
Readme  SteamCMD Link fix

### ISSUE THREAD

**Issue by GerasimosKan** [QuintenQVD0/Q_eggs#133]
the new working link 

curl -sSL https://raw.githubusercontent.com/QuintenQVD0/Q_eggs/refs/heads/main/steamgames.sh | bash

**Comment by QuintenQVD0** [comment]
??

**Comment by QuintenQVD0** [comment]
https://raw.githubusercontent.com/QuintenQVD0/Q_eggs/main/steamgames.sh works just fine?
