### ISSUE TITLE
[Egg Request]: Rimworld server (Open World mod)

### ISSUE THREAD

**Issue by Redstylt** [QuintenQVD0/Q_eggs#15]
### Does this expand an already existing service

No

### Link to a game or software

https://steamcommunity.com/sharedfiles/filedetails/?id=2768146099

### Links for the download

https://github.com/TastyLollipop/OpenWorld/releases/tag/1.4.0

### Links for the install docs

https://openworldhelp.fandom.com/wiki/Open_World_Wiki

### Does this app work on ARM?

Yes

**Comment by Redstylt** [comment]
Also lots of info can be found on the discord https://discord.gg/SNtVjR6bqU
Thx for your time

**Comment by Redstylt** [comment]
And this egg is meant to run on a Oracle Cloud Tier free

**Comment by QuintenQVD0** [comment]
I take a look as soon as I can!

**Comment by QuintenQVD0** [comment]
I currently have a working egg only it is not possible to parse the config to auto set the game port because it is a .txt file
@Redstylt

**Comment by Redstylt** [comment]
I don't know if it can help you but here's the install script of my friend who parsed the server port
`#!/bin/bash
DEBIAN_FRONTEND=noninteractive

apt -y update
apt -y install p7zip-full
apt -y install curl


echo -e "Installing game server files"
cd /mnt/server/
curl https://github.com/TastyLollipop/OpenWorld/releases/latest/download/ARMX64_SelfContained.zip -O -J -L
7z x ARMX64_SelfContained.zip
mv "Open World Server" "OpenWorldServer"
chmod +x OpenWorldServer
cd ./home/container/


echo -n "- Server Details -
Server Name: My Server Name
Server Description: My Server Description
Server Local IP: 0.0.0.0
Server Port: ${SERVER_PORT}
Max Players: 300
Allow Dev Mode: False
Use Whitelist: False

- Mod System Details -
Use Modlist Match: True
Use Modlist Config Match (WIP): False
Force Mod Verification: False

- Chat System Details -
Use Chat: True
Use Profanity filter: True

- Wealth System Details -
Use Wealth System: False
Wealth Warning Threshold: 10000
Wealth Ban Threshold: 100000

- Idle System Details -
Use Idle System: True
Idle Threshold (days): 7

- Road System Details -
Use Road System: True
Aggressive Road Mode (WIP): False
" > "Server Settings.txt"

echo -e "Your server's configuration file has been created, go to /file/ and look for settings.txt to edit"
echo -e " "

echo -e "Your server port is ${SERVER_PORT}"`

**Comment by QuintenQVD0** [comment]
thx but we can not use the selfcontainerd one. we must use the regular one but I have a look
