### ISSUE TITLE
[Egg Request]: Counter-Strike: Global Offensive (steamcmd)

### ISSUE THREAD

**Issue by Gahtee** [QuintenQVD0/Q_eggs#19]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/730/CounterStrike_Global_Offensive/

### Links for the download

https://store.steampowered.com/app/730/CounterStrike_Global_Offensive/

### Links for the install docs

https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Dedicated_Servers

### Does this app work on ARM?

No

**Comment by QuintenQVD0** [comment]
It is a steam game, there is a litte changes this will work on a pi 4 but not on oracle cloud, but I can try

**Comment by Gahtee** [comment]
why it wouldn’t run in oracle cloud?

**Comment by QuintenQVD0** [comment]
https://github.com/QuintenQVD0/Q_eggs/issues/17#issuecomment-1295749231 oracle clous kernel does not like emulation

**Comment by QuintenQVD0** [comment]
I maby have a Idea but I need your help

Run this on the host OS, it will take some time like 20 min +
```sh
curl -sSL https://raw.githubusercontent.com/QuintenQVD0/Q_eggs/steamcmd/steamgames.sh | bash
```
If you have any error with this let me know. If that installs fine then you can try this: https://github.com/QuintenQVD0/Q_eggs/blob/e8f6b8fbd7ce892edd02c6635dc8e424c936976d/egg-counter--strike--global-offensive.json

**Comment by Gahtee** [comment]
worked pefectly, even 128 tickrate worked. it is awesome, thanks
