### ISSUE TITLE
BeamMP for ARM64 Egg Request

### ISSUE THREAD

**Issue by FloofyCandy** [QuintenQVD0/Q_eggs#2]
Link to game: https://github.com/BeamMP/BeamMP-Server

Links for server downloads: https://beammp.com/

Links for install steps/docs: https://github.com/BeamMP/BeamMP-Server/releases/

**Comment by QuintenQVD0** [comment]
> Link to game: https://github.com/BeamMP/BeamMP-Server
> 
> Links for server downloads: https://beammp.com/
> 
> Links for install steps/docs: https://github.com/BeamMP/BeamMP-Server/releases/

I will try to make one, I have no idea if it will even work

**Comment by FloofyCandy** [comment]
Haha it works, you are amazing and thx so much!
