### ISSUE TITLE
[Egg Request]: STEAMCMD RUST (ORACLE ARM)

### ISSUE THREAD

**Issue by TayGG** [QuintenQVD0/Q_eggs#26]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/252490/Rust/

### Links for the download

https://rust.fandom.com/wiki/Host_your_own_server/

### Links for the install docs

https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/rust/

### Does this app work on ARM?

No

**Comment by QuintenQVD0** [comment]
I will have a look at the end of next week. ,then I have time

**Comment by TayGG** [comment]
ok

**Comment by TayGG** [comment]
```
{
    "_comment": "DO NOT EDIT: FILE GENERATED AUTOMATICALLY BY PTERODACTYL PANEL - PTERODACTYL.IO",
    "meta": {
        "version": "PTDL_v2",
        "update_url": null
    },
    "exported_at": "2022-11-26T11:35:12+01:00",
    "name": "Rust Autowipe (Custom Test)",
    "author": "example@example.com",
    "description": "The only aim in Rust is to survive. To do this you will need to overcome struggles such as hunger, thirst and cold. Build a fire. Build a shelter. Kill animals for meat. Protect yourself from other players, and kill them for meat. Create alliances with other players and form a town. Do whatever it takes to survive.",
    "features": [
        "steam_disk_space"
    ],
    "docker_images": {
        "Emulation": "quintenqvd\/pterodactyl_images:emulation"
    },
    "file_denylist": [],
    "startup": "\".\/RustDedicated -batchmode +server.port {{SERVER_PORT}} +server.identity \"rust\" +rcon.ip 0.0.0.0 +rcon.port {{RCON_PORT}} +rcon.web true +server.hostname \\\"{{HOSTNAME}}\\\" +server.level \\\"{{LEVEL}}\\\" +server.description \\\"{{DESCRIPTION}}\\\" +server.url \\\"{{SERVER_URL}}\\\" +server.headerimage \\\"{{SERVER_IMG}}\\\" +server.worldsize \\\"{{WORLD_SIZE}}\\\" +server.seed \\\"$( if [ -f seed.txt ] && [[ ${WORLD_SEED} == \"0\" ]]; then printf %s $(cat seed.txt); else printf %s '${WORLD_SEED}'; fi )\\\" +server.maxplayers {{MAX_PLAYERS}} +rcon.password \\\"{{RCON_PASS}}\\\" +server.saveinterval {{SAVEINTERVAL}} {{ADDITIONAL_ARGS}}\"",
    "config": {
        "files": "{}",
        "startup": "{\r\n    \"done\": \"Server startup complete\"\r\n}",
        "logs": "{}",
        "stop": "quit"
    },
    "scripts": {
        "installation": {
            "script": "#!\/bin\/bash\r\n# steamcmd Base Installation Script\r\n#\r\n# Server Files: \/mnt\/server\r\n# Image to install with is 'ubuntu:18.04'\r\n\r\n## just in case someone removed the defaults.\r\nif [ \"${STEAM_USER}\" == \"\" ]; then\r\n    STEAM_USER=anonymous\r\n    STEAM_PASS=\"\"\r\n    STEAM_AUTH=\"\"\r\nfi\r\n\r\n## download and install steamcmd\r\ncd \/tmp\r\nmkdir -p \/mnt\/server\/steamcmd\r\ncurl -sSL -o steamcmd.tar.gz https:\/\/steamcdn-a.akamaihd.net\/client\/installer\/steamcmd_linux.tar.gz\r\ntar -xzvf steamcmd.tar.gz -C \/mnt\/server\/steamcmd\r\n\r\nmkdir -p \/mnt\/server\/Engine\/Binaries\/ThirdParty\/SteamCMD\/Linux\r\ntar -xzvf steamcmd.tar.gz -C \/mnt\/server\/Engine\/Binaries\/ThirdParty\/SteamCMD\/Linux\r\nmkdir -p \/mnt\/server\/steamapps # Fix steamcmd disk write error when this folder is missing\r\ncd \/mnt\/server\/steamcmd\r\n\r\n# SteamCMD fails otherwise for some reason, even running as root.\r\n# This is changed at the end of the install process anyways.\r\nchown -R root:root \/mnt\r\nexport HOME=\/mnt\/server\r\n\r\n## install game using steamcmd\r\n.\/steamcmd.sh +force_install_dir \/mnt\/server +login ${STEAM_USER} ${STEAM_PASS} ${STEAM_AUTH} +app_update ${SRCDS_APPID} ${EXTRA_FLAGS} +quit ## other flags may be needed depending on install. looking at you cs 1.6\r\n\r\n## set up 32 bit libraries\r\nmkdir -p \/mnt\/server\/.steam\/sdk32\r\ncp -v linux32\/steamclient.so ..\/.steam\/sdk32\/steamclient.so\r\n\r\n## set up 64 bit libraries\r\nmkdir -p \/mnt\/server\/.steam\/sdk64\r\ncp -v linux64\/steamclient.so ..\/.steam\/sdk64\/steamclient.so\r\n\r\n## create a symbolic link for loading mods\r\ncd \/mnt\/server\/Engine\/Binaries\/ThirdParty\/SteamCMD\/Linux\r\nln -sf ..\/..\/..\/..\/..\/Steam\/steamapps steamapps\r\ncd \/mnt\/server\r\necho \"done\"",
            "container": "quintenqvd\/pterodactyl_images:installer_steamcmd",
            "entrypoint": "bash"
        }
    },
    "variables": [
        {
            "name": "Server Name",
            "description": "The name of your server in the public server list.",
            "env_variable": "HOSTNAME",
            "default_value": "A Rust Server",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|string|max:40",
            "field_type": "text"
        },
        {
            "name": "OxideMod",
            "description": "Set whether you want the server to use and auto update OxideMod or not. Valid options are \"1\" for true and \"0\" for false.",
            "env_variable": "OXIDE",
            "default_value": "0",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|boolean",
            "field_type": "text"
        },
        {
            "name": "Level",
            "description": "The world file for Rust to use.",
            "env_variable": "LEVEL",
            "default_value": "Procedural Map",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|string|max:20",
            "field_type": "text"
        },
        {
            "name": "Description",
            "description": "The description under your server title. Commonly used for rules & info. Use \\n for newlines.",
            "env_variable": "DESCRIPTION",
            "default_value": "Powered by Pterodactyl",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|string",
            "field_type": "text"
        },
        {
            "name": "URL",
            "description": "The URL for your server. This is what comes up when clicking the \"Visit Website\" button.",
            "env_variable": "SERVER_URL",
            "default_value": "http:\/\/pterodactyl.io",
            "user_viewable": true,
            "user_editable": true,
            "rules": "nullable|url",
            "field_type": "text"
        },
        {
            "name": "World Size",
            "description": "The world size for a procedural map.",
            "env_variable": "WORLD_SIZE",
            "default_value": "3000",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|integer",
            "field_type": "text"
        },
        {
            "name": "World Seed",
            "description": "The seed for a procedural map.",
            "env_variable": "WORLD_SEED",
            "default_value": "0",
            "user_viewable": true,
            "user_editable": true,
            "rules": "nullable|string",
            "field_type": "text"
        },
        {
            "name": "Max Players",
            "description": "The maximum amount of players allowed in the server at once.",
            "env_variable": "MAX_PLAYERS",
            "default_value": "40",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|integer",
            "field_type": "text"
        },
        {
            "name": "Server Image",
            "description": "The header image for the top of your server listing.",
            "env_variable": "SERVER_IMG",
            "default_value": "",
            "user_viewable": true,
            "user_editable": true,
            "rules": "nullable|url",
            "field_type": "text"
        },
        {
            "name": "RCON Port",
            "description": "Port for RCON connections.",
            "env_variable": "RCON_PORT",
            "default_value": "28016",
            "user_viewable": true,
            "user_editable": false,
            "rules": "required|integer",
            "field_type": "text"
        },
        {
            "name": "RCON Password",
            "description": "RCON access password.",
            "env_variable": "RCON_PASS",
            "default_value": "CHANGEME",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|regex:\/^[\\w.-]*$\/|max:64",
            "field_type": "text"
        },
        {
            "name": "Save Interval",
            "description": "Sets the server\u2019s auto-save interval in seconds.",
            "env_variable": "SAVEINTERVAL",
            "default_value": "60",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|integer",
            "field_type": "text"
        },
        {
            "name": "Additional Arguments",
            "description": "Add additional startup parameters to the server.",
            "env_variable": "ADDITIONAL_ARGS",
            "default_value": "",
            "user_viewable": true,
            "user_editable": true,
            "rules": "nullable|string",
            "field_type": "text"
        },
        {
            "name": "Regen Server",
            "description": "If the server should have its files removed and regenerate the server seed on reinstall.",
            "env_variable": "REGEN_SERVER",
            "default_value": "0",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|boolean",
            "field_type": "text"
        },
        {
            "name": "Files to remove",
            "description": "A space-separated list of files to remove when regenerating the server on reinstall.",
            "env_variable": "REMOVE_FILES",
            "default_value": "server\/rust\/player.deaths.*.db server\/rust\/player.identities.*.db server\/rust\/player.states.*.db server\/rust\/player.tokens.db proceduralmap.*.*.*.map server\/rust\/proceduralmap.*.*.*.sav oxide\/data\/Kits_Data.json oxide\/data\/NTeleportationHome.json oxide\/data\/ServerRewards\/player_data.json oxide\/data\/PTTracker\/playtime_data.json",
            "user_viewable": true,
            "user_editable": true,
            "rules": "required|string",
            "field_type": "text"
        },
        {
            "name": "SRCDS_APPID",
            "description": "",
            "env_variable": "SRCDS_APPID",
            "default_value": "258550",
            "user_viewable": false,
            "user_editable": false,
            "rules": "required|string|max:20",
            "field_type": "text"
        }
    ]
}
```

Did this, it works fine at first. It install everything, but wen the server is loading it crash, dont know if this helps, but i tried what i could (even knowing nothing of custom eggs, docker images, etc XDDDD)

**Comment by QuintenQVD0** [comment]
> ```
> {
>     "_comment": "DO NOT EDIT: FILE GENERATED AUTOMATICALLY BY PTERODACTYL PANEL - PTERODACTYL.IO",
>     "meta": {
>         "version": "PTDL_v2",
>         "update_url": null
>     },
>     "exported_at": "2022-11-26T11:35:12+01:00",
>     "name": "Rust Autowipe (Custom Test)",
>     "author": "example@example.com",
>     "description": "The only aim in Rust is to survive. To do this you will need to overcome struggles such as hunger, thirst and cold. Build a fire. Build a shelter. Kill animals for meat. Protect yourself from other players, and kill them for meat. Create alliances with other players and form a town. Do whatever it takes to survive.",
>     "features": [
>         "steam_disk_space"
>     ],
>     "docker_images": {
>         "Emulation": "quintenqvd\/pterodactyl_images:emulation"
>     },
>     "file_denylist": [],
>     "startup": "\".\/RustDedicated -batchmode +server.port {{SERVER_PORT}} +server.identity \"rust\" +rcon.ip 0.0.0.0 +rcon.port {{RCON_PORT}} +rcon.web true +server.hostname \\\"{{HOSTNAME}}\\\" +server.level \\\"{{LEVEL}}\\\" +server.description \\\"{{DESCRIPTION}}\\\" +server.url \\\"{{SERVER_URL}}\\\" +server.headerimage \\\"{{SERVER_IMG}}\\\" +server.worldsize \\\"{{WORLD_SIZE}}\\\" +server.seed \\\"$( if [ -f seed.txt ] && [[ ${WORLD_SEED} == \"0\" ]]; then printf %s $(cat seed.txt); else printf %s '${WORLD_SEED}'; fi )\\\" +server.maxplayers {{MAX_PLAYERS}} +rcon.password \\\"{{RCON_PASS}}\\\" +server.saveinterval {{SAVEINTERVAL}} {{ADDITIONAL_ARGS}}\"",
>     "config": {
>         "files": "{}",
>         "startup": "{\r\n    \"done\": \"Server startup complete\"\r\n}",
>         "logs": "{}",
>         "stop": "quit"
>     },
>     "scripts": {
>         "installation": {
>             "script": "#!\/bin\/bash\r\n# steamcmd Base Installation Script\r\n#\r\n# Server Files: \/mnt\/server\r\n# Image to install with is 'ubuntu:18.04'\r\n\r\n## just in case someone removed the defaults.\r\nif [ \"${STEAM_USER}\" == \"\" ]; then\r\n    STEAM_USER=anonymous\r\n    STEAM_PASS=\"\"\r\n    STEAM_AUTH=\"\"\r\nfi\r\n\r\n## download and install steamcmd\r\ncd \/tmp\r\nmkdir -p \/mnt\/server\/steamcmd\r\ncurl -sSL -o steamcmd.tar.gz https:\/\/steamcdn-a.akamaihd.net\/client\/installer\/steamcmd_linux.tar.gz\r\ntar -xzvf steamcmd.tar.gz -C \/mnt\/server\/steamcmd\r\n\r\nmkdir -p \/mnt\/server\/Engine\/Binaries\/ThirdParty\/SteamCMD\/Linux\r\ntar -xzvf steamcmd.tar.gz -C \/mnt\/server\/Engine\/Binaries\/ThirdParty\/SteamCMD\/Linux\r\nmkdir -p \/mnt\/server\/steamapps # Fix steamcmd disk write error when this folder is missing\r\ncd \/mnt\/server\/steamcmd\r\n\r\n# SteamCMD fails otherwise for some reason, even running as root.\r\n# This is changed at the end of the install process anyways.\r\nchown -R root:root \/mnt\r\nexport HOME=\/mnt\/server\r\n\r\n## install game using steamcmd\r\n.\/steamcmd.sh +force_install_dir \/mnt\/server +login ${STEAM_USER} ${STEAM_PASS} ${STEAM_AUTH} +app_update ${SRCDS_APPID} ${EXTRA_FLAGS} +quit ## other flags may be needed depending on install. looking at you cs 1.6\r\n\r\n## set up 32 bit libraries\r\nmkdir -p \/mnt\/server\/.steam\/sdk32\r\ncp -v linux32\/steamclient.so ..\/.steam\/sdk32\/steamclient.so\r\n\r\n## set up 64 bit libraries\r\nmkdir -p \/mnt\/server\/.steam\/sdk64\r\ncp -v linux64\/steamclient.so ..\/.steam\/sdk64\/steamclient.so\r\n\r\n## create a symbolic link for loading mods\r\ncd \/mnt\/server\/Engine\/Binaries\/ThirdParty\/SteamCMD\/Linux\r\nln -sf ..\/..\/..\/..\/..\/Steam\/steamapps steamapps\r\ncd \/mnt\/server\r\necho \"done\"",
>             "container": "quintenqvd\/pterodactyl_images:installer_steamcmd",
>             "entrypoint": "bash"
>         }
>     },
>     "variables": [
>         {
>             "name": "Server Name",
>             "description": "The name of your server in the public server list.",
>             "env_variable": "HOSTNAME",
>             "default_value": "A Rust Server",
>             "user_viewable": true,
>             "user_editable": true,
>             "rules": "required|string|max:40",
>             "field_type": "text"
>         },
>         {
>             "name": "OxideMod",
>             "description": "Set whether you want the server to use and auto update OxideMod or not. Valid options are \"1\" for true and \"0\" for false.",
>             "env_variable": "OXIDE",
>             "default_value": "0",
>             "user_viewable": true,
>             "user_editable": true,
>             "rules": "required|boolean",
>             "field_type": "text"
>         },
>         {
>             "name": "Level",
>             "description": "The world file for Rust to use.",
>             "env_variable": "LEVEL",
>             "default_value": "Procedural Map",
>             "user_viewable": true,
>             "user_editable": true,
>             "rules": "required|string|max:20",
>             "field_type": "text"
>         },
>         {
>             "name": "Description",
>             "description": "The description under your server title. Commonly used for rules & info. Use \\n for newlines.",
>             "env_variable": "DESCRIPTION",
>             "default_value": "Powered by Pterodactyl",
>             "user_viewable": true,
>             "user_editable": true,
>             "rules": "required|string",
>             "field_type": "text"
>         },
>         {
>             "name": "URL",
>             "description": "The URL for your server. This is what comes up when clicking the \"Visit Website\" button.",
>             "env_variable": "SERVER_URL",
>             "default_value": "http:\/\/pterodactyl.io",
>             "user_viewable": true,
>             "user_editable": true,
>             "rules": "nullable|url",
>             "field_type": "text"
>         },
>         {
>             "name": "World Size",
>             "description": "The world size for a procedural map.",
>             "env_variable": "WORLD_SIZE",
>             "default_value": "3000",
>             "user_viewable": true,
>             "user_editable": true,
>             "rules": "required|integer",
>             "field_type": "text"
>         },
>         {
>             "name": "World Seed",
>             "description": "The seed for a procedural map.",
>             "env_variable": "WORLD_SEED",
>             "default_value": "0",
>             "user_viewable": true,
>             "user_editable": true,
>             "rules": "nullable|string",
>             "field_type": "text"
>         },
>         {
>             "name": "Max Players",
>             "description": "The maximum amount of players allowed in the server at once.",
>             "env_variable": "MAX_PLAYERS",
>             "default_value": "40",
>             "user_viewable": true,
>             "user_editable": true,
>             "rules": "required|integer",
>             "field_type": "text"
>         },
>         {
>             "name": "Server Image",
>             "description": "The header image for the top of your server listing.",
>             "env_variable": "SERVER_IMG",
>             "default_value": "",
>             "user_viewable": true,
>             "user_editable": true,
>             "rules": "nullable|url",
>             "field_type": "text"
>         },
>         {
>             "name": "RCON Port",
>             "description": "Port for RCON connections.",
>             "env_variable": "RCON_PORT",
>             "default_value": "28016",
>             "user_viewable": true,
>             "user_editable": false,
>             "rules": "required|integer",
>             "field_type": "text"
>         },
>         {
>             "name": "RCON Password",
>             "description": "RCON access password.",
>             "env_variable": "RCON_PASS",
>             "default_value": "CHANGEME",
>             "user_viewable": true,
>             "user_editable": true,
>             "rules": "required|regex:\/^[\\w.-]*$\/|max:64",
>             "field_type": "text"
>         },
>         {
>             "name": "Save Interval",
>             "description": "Sets the server\u2019s auto-save interval in seconds.",
>             "env_variable": "SAVEINTERVAL",
>             "default_value": "60",
>             "user_viewable": true,
>             "user_editable": true,
>             "rules": "required|integer",
>             "field_type": "text"
>         },
>         {
>             "name": "Additional Arguments",
>             "description": "Add additional startup parameters to the server.",
>             "env_variable": "ADDITIONAL_ARGS",
>             "default_value": "",
>             "user_viewable": true,
>             "user_editable": true,
>             "rules": "nullable|string",
>             "field_type": "text"
>         },
>         {
>             "name": "Regen Server",
>             "description": "If the server should have its files removed and regenerate the server seed on reinstall.",
>             "env_variable": "REGEN_SERVER",
>             "default_value": "0",
>             "user_viewable": true,
>             "user_editable": true,
>             "rules": "required|boolean",
>             "field_type": "text"
>         },
>         {
>             "name": "Files to remove",
>             "description": "A space-separated list of files to remove when regenerating the server on reinstall.",
>             "env_variable": "REMOVE_FILES",
>             "default_value": "server\/rust\/player.deaths.*.db server\/rust\/player.identities.*.db server\/rust\/player.states.*.db server\/rust\/player.tokens.db proceduralmap.*.*.*.map server\/rust\/proceduralmap.*.*.*.sav oxide\/data\/Kits_Data.json oxide\/data\/NTeleportationHome.json oxide\/data\/ServerRewards\/player_data.json oxide\/data\/PTTracker\/playtime_data.json",
>             "user_viewable": true,
>             "user_editable": true,
>             "rules": "required|string",
>             "field_type": "text"
>         },
>         {
>             "name": "SRCDS_APPID",
>             "description": "",
>             "env_variable": "SRCDS_APPID",
>             "default_value": "258550",
>             "user_viewable": false,
>             "user_editable": false,
>             "rules": "required|string|max:20",
>             "field_type": "text"
>         }
>     ]
> }
> ```
> 
> Did this, it works fine at first. It install everything, but wen the server is loading it crash, dont know if this helps, but i tried what i could (even knowing nothing of custom eggs, docker images, etc XDDDD)

Thx ,it is a beginning but it will need a custom image aq it is not by default using the source image

**Comment by QuintenQVD0** [comment]
Just for development,  can you run file againt the rust bin for me?

**Comment by TayGG** [comment]
Sorry if i dont understand your question (im spanish)
Do you mean running the "RustDedicated" file?

It wont run, i did a .sh file with the startup and then It works

**Comment by QuintenQVD0** [comment]
> Sorry if i dont understand your question (im spanish) Do you mean running the "RustDedicated" file?
> 
> It wont run, i did a .sh file with the startup and then It works

Did you even setup steamcmd on the host? as is needed with all steamcmd games? I am building a new image rn and in 8 hours I can try and see if it works

**Comment by QuintenQVD0** [comment]
> Ahhh, you mean this? `curl -sSL https://raw.githubusercontent.com/QuintenQVD0/Q_eggs/main/steamgames.sh | bash`
> 
> Yeah i did it

Yes I mean that

can you show me the output on the host of
`box86 --version`
and
`box64 --version`

If it does not trow a error try this as the server image: `quintenqvd/pterodactyl_images:games_rust`

**Comment by TayGG** [comment]
box86 --version
Box86 with Dynarec v0.2.9 3fcdee46 built on Nov 29 2022 21:24:16

box64 --version
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Cores:4
Params database has 10 entries
Box64 with Dynarec v0.2.1 c08268d0 built on Nov 29 2022 21:27:11


Ill try the image

**Comment by QuintenQVD0** [comment]
> box86 --version Box86 with Dynarec v0.2.9 3fcdee46 built on Nov 29 2022 21:24:16
> 
> box64 --version Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Cores:4 Params database has 10 entries Box64 with Dynarec v0.2.1 c08268d0 built on Nov 29 2022 21:27:11
> 
> Ill try the image

Let me know if it works, if not then I have a look later this day

**Comment by TayGG** [comment]
At first it works. But when it finish generating the map i got this:

```
Connected to RCON. Generating the map now. Please wait until the server status switches to "Running".
hostname: A Rust Server
version : 2362 secure (secure mode enabled, connected to Steam3)
map     : Procedural Map
players : 0 (40 max) (0 queued) (0 joining)
id name ping connected addr owner violation kicks 
        done.
Initializing 350 stability supports
        done.
Initializing 32284 entity save caches
        15959 / 32284
        done.
Gamemode Convar :vanilla
Installed : 0spawn points.
Game created! type was : assets/prefabs/gamemodes/vanilla.prefab
Couldn't initialize Steam Server (InitGameServer returned false (0,0,28015,65535,3,"2362"))
NullReferenceException: Object reference not set to an instance of an object
Connection to server closed.
```

**Comment by QuintenQVD0** [comment]
> Couldn't initialize Steam Server (InitGameServer returned false (0,0,28015,65535,3,"2362"))

You running uMod?

**Comment by TayGG** [comment]
yeh

**Comment by TayGG** [comment]
Ok, ill remove it and try again

**Comment by QuintenQVD0** [comment]
> oh i see

The both use the LD_LIBRARY_PATH : the emulator and umod so that will not work

**Comment by TayGG** [comment]
still geting the same error

**Comment by QuintenQVD0** [comment]
> still geting the same error

I have a look later in like 4 hours

**Comment by QuintenQVD0** [comment]
I can not realy test this aq my pi 4 only has 4 gb of ram and it needs overhead. So it just crashes. And i can nog get a oracle instance.

**Comment by TayGG** [comment]
If you want i can give you access to our testing server on our panel. I mean, i cant give you admin un the panel, (nothing personal, just security) but i can set the egg  and imagen that you provide, and you can see the console's logs so you can know whats happenint. (I dont know if im explaining muy self very well, let me know if you dont understand something)

**Comment by QuintenQVD0** [comment]
> If you want i can give you access to our testing server on our panel. I mean, i cant give you admin un the panel, (nothing personal, just security) but i can set the egg and imagen that you provide, and you can see the console's logs so you can know whats happenint. (I dont know if im explaining muy self very well, let me know if you dont understand something)

That would be nice but that wouldn't realy help me as I need to make changes to the startup cmd and make and test out variables.

**Comment by nadirali01** [comment]
hey Quinten. i try normal vanilla mod. but still getting same issue. everything working fine just crash when server is on, can you changes some egg or something to work just vanilla? if you need server i given for test ?

**Comment by QuintenQVD0** [comment]
> hey Quinten. i try normal vanilla mod. but still getting same issue. everything working fine just crash when server is on, can you changes some egg or something to work just vanilla? if you need server i given for test ?

As far aq I know the emmulator is currently not anble to handle rust

**Comment by nadirali01** [comment]
> > hey Quinten. i try normal vanilla mod. but still getting same issue. everything working fine just crash when server is on, can you changes some egg or something to work just vanilla? if you need server i given for test ?
> 
> As far aq I know the emmulator is currently not anble to handle rust

and did you check other emu, qemu and more emu avlb for ARM ?

**Comment by QuintenQVD0** [comment]
> 

Qemu needs root. And avlb i did not tesr

**Comment by QuintenQVD0** [comment]
it does not work as long as the emulator does not fix it. so for now I closes this
