### ISSUE TITLE
[Egg Request]: RAGE MP (Oracle ARM)

### ISSUE THREAD

**Issue by JaredHuh** [QuintenQVD0/Q_eggs#35]
### Does this expand an already existing service

No

### Link to a game or software

https://rage.mp

### Links for the download

https://cdn.rage.mp/updater/prerelease/server-files/linux_x64.tar.gz

### Links for the install docs

https://wiki.rage.mp/index.php?title=Getting_Started_with_Server

### Does this app work on ARM?

I don't know

**Comment by QuintenQVD0** [comment]
It does work,  i post it later

**Comment by JaredHuh** [comment]
Okay!

**Comment by QuintenQVD0** [comment]
added

**Comment by JaredHuh** [comment]
Thank you so much, but there is a problem. I start it up, it starts running normally and suddenly an error pops up. I have not changed anything in the egg.

log:
https://pastebin.com/yUyeBuHB
