### ISSUE TITLE
[Egg Request]: NodeJS Puppeteer for Arm

### ISSUE THREAD

**Issue by Gahtee** [QuintenQVD0/Q_eggs#38]
### Does this expand an already existing service

Yes

### Link to a game or software

https://pptr.dev https://nodejs.org/en/

### Links for the download

https://pptr.dev/chromium-support

### Links for the install docs

https://pptr.dev/guides/docker

### Does this app work on ARM?

No

**Comment by QuintenQVD0** [comment]
this is not realy posible as you need `chrome`=amd64 only and not `chromium`=both

**Comment by QuintenQVD0** [comment]
so not posible, sorry
