### ISSUE TITLE
[Egg Request]:  Assetto Corsa

### ISSUE THREAD

**Issue by serverkur** [QuintenQVD0/Q_eggs#39]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/assetto_corsa

### Links for the download

https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/assetto_corsa

### Links for the install docs

https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/assetto_corsa

### Does this app work on ARM?

I don't know

**Comment by QuintenQVD0** [comment]
I will have a look as soon as i can

**Comment by serverkur** [comment]
https://github.com/compujuckel/AssettoServer/releases/tag/v0.0.51

and use this.

I was able to run
![image](https://user-images.githubusercontent.com/36241002/225749253-d1e5bbc9-2d0d-442f-9b39-e58f7c72ccb9.png)

**Comment by serverkur** [comment]
arm64 oracle

**Comment by QuintenQVD0** [comment]
> arm64 oracle

Not what i asked. Run file against the bin and send the result here. I need to know if it is 32 bit or 64

**Comment by QuintenQVD0** [comment]
I do it later myself

**Comment by QuintenQVD0** [comment]
how did you get the ./acserver as they mentionion it is windows only

**Comment by QuintenQVD0** [comment]
I found it! But you need a steam account that owns that game berfore you can download it

**Comment by serverkur** [comment]
i pterodactly assetto corsa egini i combined the egg you made for csgo did not work the first time because dotnet was missing so i asked you for an egg 


but i was able to run it directly on sshhttps://github.com/compujuckel/AssettoServer/releases/tag/v0.0.51

acserver available in the arm file here

**Comment by QuintenQVD0** [comment]
> i pterodactly assetto corsa egg i combined the egg you made for csgo did not work the first time because dotnet was missing so i asked you for an egg
> 
> but i was able to run it directly on ssh https://github.com/compujuckel/AssettoServer/releases/tag/v0.0.51
> 
> acserver available in the arm file here

that is not the offical server, that is a modification and not using steamcmd

**Comment by serverkur** [comment]
This is generally used for assetto corsa, I haven't seen anyone using steamcmd

**Comment by QuintenQVD0** [comment]
> This is generally used for assetto corsa, I haven't seen anyone using steamcmd

it is complaining about config files not found, do you have some full config files?

**Comment by serverkur** [comment]
servercfg?

https://hastebin.com/share/runohojapu.makefile

**Comment by QuintenQVD0** [comment]
> servercfg?
> 
> https://hastebin.com/share/runohojapu.makefile

yea, it is not self generating it for me..

**Comment by QuintenQVD0** [comment]
but I make it as soon as posible

**Comment by serverkur** [comment]
ok i'm following.

**Comment by QuintenQVD0** [comment]
@serverkur Sorry for the very late response but can you please resend a default config. as I know know how to use a other emulator that works I guess better for this

**Comment by exababy** [comment]
https://assettoserver.org/

[SERVER]
NAME=AC_Server
CARS=bmw_m3_e30
CONFIG_TRACK=
TRACK=magione
SUN_ANGLE=48
PASSWORD=
ADMIN_PASSWORD=mypassword
UDP_PORT=9600
TCP_PORT=9600
HTTP_PORT=8081
PICKUP_MODE_ENABLED=1
LOOP_MODE=1
SLEEP_TIME=1
CLIENT_SEND_INTERVAL_HZ=18
SEND_BUFFER_SIZE=0
RECV_BUFFER_SIZE=0
RACE_OVER_TIME=180
KICK_QUORUM=85
VOTING_QUORUM=80
VOTE_DURATION=20
BLACKLIST_MODE=1
FUEL_RATE=100
DAMAGE_MULTIPLIER=100
TYRE_WEAR_RATE=100
ALLOWED_TYRES_OUT=2
ABS_ALLOWED=1
TC_ALLOWED=1
STABILITY_ALLOWED=0
AUTOCLUTCH_ALLOWED=0
TYRE_BLANKETS_ALLOWED=0
FORCE_VIRTUAL_MIRROR=1
REGISTER_TO_LOBBY=1
MAX_CLIENTS=18
UDP_PLUGIN_LOCAL_PORT=0
UDP_PLUGIN_ADDRESS=
AUTH_PLUGIN_ADDRESS=
LEGAL_TYRES=SV

[PRACTICE]
NAME=Practice
TIME=10
IS_OPEN=1

[QUALIFY]
NAME=Qualify
TIME=10
IS_OPEN=1

[RACE]
NAME=Race
LAPS=5
WAIT_TIME=60
IS_OPEN=1

[DYNAMIC_TRACK]
SESSION_START=89
RANDOMNESS=3
SESSION_TRANSFER=80
LAP_GAIN=50

[WEATHER_0]
GRAPHICS=3_clear
BASE_TEMPERATURE_AMBIENT=18
BASE_TEMPERATURE_ROAD=6
VARIATION_AMBIENT=1
VARIATION_ROAD=1

[WEATHER_1]
GRAPHICS=7_heavy_clouds
BASE_TEMPERATURE_AMBIENT=15
BASE_TEMPERATURE_ROAD=-1
VARIATION_AMBIENT=1
VARIATION_ROAD=1

**Comment by QuintenQVD0** [comment]
I added the egg for it so I am closing this.

 https://github.com/compujuckel/AssettoServer/releases
