### ISSUE TITLE
[Bug]: SCP: Secret Laboratory Exiled server won't start

### ISSUE THREAD

**Issue by ThijmenNLD** [QuintenQVD0/Q_eggs#45]
### Panel Version

1.11.3

### Wings Version

1.11.5

### Service

SCP: Secret Laboratory Exiled

### Modified

No, I did not modify the egg

### Expected Behavior

When I press run the server will start without any issues

### Actual Behavior

When I press run the server starts but gives an error: "No usable version of libssl was found"
<img width="862" alt="ScpSlExiledArm64Error" src="https://user-images.githubusercontent.com/73742011/228005467-0ed10a78-496d-46df-849f-8f578e252f08.png">

### Steps To Reproduce

1. Install the server
2. Run the server
3. Get the error

### Install logs

https://pteropaste.com/6b25j2ckqjmh

**Comment by ThijmenNLD** [comment]
Also I wanted to say there is a spelling mistake in the README.md file. It says Ark survival evikved instead of Ark survival evolved in the Service section

**Comment by ThijmenNLD** [comment]
May I ask if there is anything I can provide you to help you solve this problem?

**Comment by QuintenQVD0** [comment]
> May I ask if there is anything I can provide you to help you solve this problem?

It can try to move to a ubuntu 20.04 and not 22.04

**Comment by QuintenQVD0** [comment]
@ThijmenNLD 

In about 45 minutes from this message a update of the image will be pushed.

For this to work, first remove NOW the folder call rootfs and remove the file called Config.json

When the image update pushes, ( so in 45 minutes) you can hit start again and it will download a new rootfs and a new Config.json

**Comment by ThijmenNLD** [comment]
I have deleted the folder rootfs and the file Config.json. Do I need to do anything special now?

**Comment by QuintenQVD0** [comment]
> I have deleted the folder rootfs and the file Config.json. Do I need to do anything special now?

No, just hit start again on the server
