### ISSUE TITLE
[Egg Request]: Garry’s Mod

### ISSUE THREAD

**Issue by QuintenQVD0** [QuintenQVD0/Q_eggs#47]
### Does this expand an already existing service

No

### Link to a game or software

https://steamcommunity.com/

### Links for the download

https://steamdb.info/app/4020/info/

### Links for the install docs

https://wiki.facepunch.com/gmod/Downloading_a_Dedicated_Server

### Does this app work on ARM?

I don't know

**Comment by QuintenQVD0** [comment]
I tried this with both emulators, it did not work

**Comment by SirPlancake** [comment]
> I tried this with both emulators, it did not work

I've tried some things from the CSGO egg, and got it working completely fine.
[egg-garrys-mod.json](https://github.com/QuintenQVD0/Q_eggs/files/13443414/egg-garrys-mod.json)
