### ISSUE TITLE
[Bug]: Counter-Strike Global Offensive using ARM64 on Oracle Cloud

### ISSUE THREAD

**Issue by HalfdanDK** [QuintenQVD0/Q_eggs#49]
### Panel Version

1.11.3

### Wings Version

1.11.6

### Service

counter strike global offensive

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, start the server and join the server

### Actual Behavior

container@pterodactyl~ Starting installation process, this could take a few minutes...
steamcmd.sh
linux32/steamcmd
linux32/steamerrorreporter
linux32/libstdc++.so.6
linux32/crashhandler.so
./steamcmd.sh: line 37: /mnt/server/steamcmd/linux32/steamcmd: cannot execute binary file: Exec format error
cp: cannot stat 'linux32/steamclient.so': No such file or directory
cp: cannot stat 'linux64/steamclient.so': No such file or directory
-----------------------------------------
Installation completed...
-----------------------------------------
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from quintenqvd/pterodactyl_images 
Digest: sha256:01596689243f7a986b6662c1d91c4265fb42da9e919870bb066100d27f5534fb 
Status: Image is up to date for quintenqvd/pterodactyl_images:emulation 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 128
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...

### Steps To Reproduce

Change nothing

### Install logs

https://pteropaste.com/1l56qkiaqhh1

**Comment by QuintenQVD0** [comment]
@HalfdanDK you did not read the readme and did not install box64  and box86 on the host os.
