### ISSUE TITLE
[Egg Request]: Rust

### ISSUE THREAD

**Issue by HalfdanDK** [QuintenQVD0/Q_eggs#50]
### Does this expand an already existing service

Yes

### Link to a game or software

https://store.steampowered.com/app/252490/Rust/

### Links for the download

https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/rust/rust_autowipe

### Links for the install docs

https://www.rustafied.com/how-to-host-your-own-rust-server

### Does this app work on ARM?

I don't know

**Comment by QuintenQVD0** [comment]
you ask for rust but you specify the auto wipe egg? wy not start with the offical panel shiped one. I try that first

**Comment by HalfdanDK** [comment]
> 

Good idea

**Comment by QuintenQVD0** [comment]
I tryed with box64 and FEX and both do not work so I mark this as not possible
