### ISSUE TITLE
[Bug] Can't start: Needed config file does not exist. 

### ISSUE THREAD

**Issue by Reddishye** [QuintenQVD0/Q_eggs#51]
### Panel Version

Request if really needed

### Wings Version

Request if really needed

### Service

SCP SL EXILED egg

### Modified

No, I did not modify the egg

### Expected Behavior

i expected to the server start lol

### Actual Behavior

:/home/container$ export FEX_APP_DATA_LOCATION=/home/container/rootfs/; export FEX_APP_CONFIG_LOCATION=/home/container/; export XDG_DATA_HOME=/home/container; export HOME=/home/container; FEXInterpreter LocalAdmin ${SERVER_PORT}
RootFS already downloaded
Needed config file does not exist. exiting

### Steps To Reproduce

Just installed the script (steamcmd.sh) and then the egg.

### Install logs

nc command not found

**Comment by QuintenQVD0** [comment]
> ### Panel Version
> Request if really needed
> 
> ### Wings Version
> Request if really needed
> 
> ### Service
> SCP SL EXILED egg
> 
> ### Modified
> No, I did not modify the egg
> 
> ### Expected Behavior
> i expected to the server start lol
> 
> ### Actual Behavior
> :/home/container$ export FEX_APP_DATA_LOCATION=/home/container/rootfs/; export FEX_APP_CONFIG_LOCATION=/home/container/; export XDG_DATA_HOME=/home/container; export HOME=/home/container; FEXInterpreter LocalAdmin ${SERVER_PORT} RootFS already downloaded Needed config file does not exist. exiting
> 
> ### Steps To Reproduce
> Just installed the script (steamcmd.sh) and then the egg.
> 
> ### Install logs
> nc command not found

Install netcat to get the logs. But remove the rootfs folder and then start again. Some logs should be printed post those

**Comment by QuintenQVD0** [comment]
was fixt in the discord as far as I remember.
