### ISSUE TITLE
[Egg Request]: EGG MTA

### ISSUE THREAD

**Issue by uNippw** [QuintenQVD0/Q_eggs#54]
### Does this expand an already existing service

Yes

### Link to a game or software

https://multitheftauto.com/

### Links for the download

https://linux.multitheftauto.com/

### Links for the install docs

https://linux.multitheftauto.com/

### Does this app work on ARM?

Yes

**Comment by uNippw** [comment]
Even though it's in experimental, I would really like it to be available. I've already tried to do it and couldn't.

**Comment by QuintenQVD0** [comment]
I will make it.

**Comment by uNippw** [comment]
You are a genius. 
Thank you :D
