### ISSUE TITLE
[Bug]: FiveM(Oracle Arm): libnss_wrapper.so from LD_PRELOAD cannot be preloaded

### ISSUE THREAD

**Issue by 85yago** [QuintenQVD0/Q_eggs#59]
### Panel Version

1.11.3

### Wings Version

1.11.7

### Service

FiveM

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, can start it, and can play

### Actual Behavior

Sometimes console show "ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libnss_wrapper.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored."
But txAdmin's console panel run, and I can do first settings.
Finally, yarn in txAdmin gets in infinite loop.

error log here.
https://gist.github.com/85yago/55e42ee31af884c1a9b682ad7cb09ffa

### Steps To Reproduce

1. setting up FiveM server
2. start server
3. receive "ERROR: ld.so: object ..." but txAdmin is running and gets in infinite loop

### Install logs

https://pteropaste.com/ap6fpynhysqo

**Comment by QuintenQVD0** [comment]
That is not an error. Just a warning. Should not prevent from running anything.

**Comment by QuintenQVD0** [comment]
But i see. It looks like it is confusing fivem. Wy do zll those games use the same variable name for extra .so files...

**Comment by 85yago** [comment]
> That is not an error. Just a warning. Should not prevent from running anything.

Oh, ok, I'll try to leave it alone a little longer.

**Comment by QuintenQVD0** [comment]
> > That is not an error. Just a warning. Should not prevent from running anything.
> 
> Oh, ok, I'll try to leave it alone a little longer.

I am making a change to the image to see if it work now. one sec

**Comment by 85yago** [comment]
> > > That is not an error. Just a warning. Should not prevent from running anything.
> > 
> > 
> > Oh, ok, I'll try to leave it alone a little longer.
> 
> I am making a change to the image to see if it work now. one sec

Thanks a lot!

**Comment by QuintenQVD0** [comment]
> > > > That is not an error. Just a warning. Should not prevent from running anything.
> > > 
> > > 
> > > Oh, ok, I'll try to leave it alone a little longer.
> > 
> > 
> > I am making a change to the image to see if it work now. one sec
> 
> Thanks a lot!

the image is rebuilding, give it 5 more minutes and then try again, it should pull a newer docker image.
If it still does not work then  Ijust the fake user wrapping for valheim and move that to an other image

**Comment by QuintenQVD0** [comment]
@85yago Image is rebuild you can try

**Comment by 85yago** [comment]
> @85yago Image is rebuild you can try

yes I confirm updating image, but it makes new error...

https://gist.github.com/85yago/dde868ff3e031015ccd3153503cb4841

**Comment by QuintenQVD0** [comment]
> > @85yago Image is rebuild you can try
> 
> yes I confirm updating image, but it makes new error...
> 
> https://gist.github.com/85yago/dde868ff3e031015ccd3153503cb4841

wow, yea that indeed is something very wrong

**Comment by QuintenQVD0** [comment]
I removed the wrapper, wait like 5 minutes and retry

**Comment by 85yago** [comment]
> I removed the wrapper, wait like 5 minutes and retry

ok.

**Comment by 85yago** [comment]
> I removed the wrapper, wait like 5 minutes and retry

yes! it's working well!!!
Thank you very much!!!!

```
Status: Downloaded newer image for quintenqvd/pterodactyl_images:dev_fex 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ cd /home/container/fivem; export FEX_APP_DATA_LOCATION=/home/container/rootfs/; export FEX_APP_CONFIG_LOCATION=/home/container/; export XDG_DATA_HOME=/home/container; FEXInterpreter /home/container/fivem/alpine/opt/cfx-server/ld-musl-x86_64.so.1 --library-path "/home/container/fivem/alpine/usr/lib/v8/:/home/container/fivem/alpine/lib/:/home/container/fivem/alpine/usr/lib/" -- /home/container/fivem/alpine/opt/cfx-server/FXServer +set citizen_dir /home/container/fivem/alpine/opt/cfx-server/citizen/ +set sv_licenseKey ${FIVEM_LICENSE} +set steam_webApiKey ${STEAM_WEBAPIKEY} +set sv_maxplayers ${MAX_PLAYERS} +set serverProfile default +set txAdminPort ${TXADMIN_PORT} $( [ "$TXADMIN_ENABLE" == "1" ] || printf %s '+exec server.cfg' )
RootFS already downloaded
Needed config file exists, skipping
[    c-server-monitor]   _______  ______                           
[    c-server-monitor]  |  ___\ \/ / ___|  ___ _ ____   _____ _ __ 
[    c-server-monitor]  | |_   \  /\___ \ / _ \ '__\ \ / / _ \ '__|
[    c-server-monitor]  |  _|  /  \ ___) |  __/ |   \ V /  __/ |   
[    c-server-monitor]  |_|   /_/\_\____/ \___|_|    \_/ \___|_|   
[    c-server-monitor] -------------------------------- monitor ---
[    c-server-monitor] 
[    c-scripting-core] Creating script environments for monitor
```
