### ISSUE TITLE
Player limit

### ISSUE THREAD

**Issue by uNippw** [QuintenQVD0/Q_eggs#60]
Is it possible to set a player limit on the egg?

**Comment by QuintenQVD0** [comment]
Wy did you ditch the template? And on what egg?

**Comment by uNippw** [comment]
Sorry, I'm talking about Multi Theft Auto

**Comment by QuintenQVD0** [comment]
I will see what I can do

**Comment by uNippw** [comment]
Okaay, thank you <3
