### ISSUE TITLE
[Egg Request]: Garry's Mod (ARM64)

### ISSUE THREAD

**Issue by SirPlancake** [QuintenQVD0/Q_eggs#61]
### Does this expand an already existing service

Yes

### Link to a game or software

https://gmod.facepunch.com/

### Links for the download

I don't know what this means.

### Links for the install docs

Its a source game. I don't know where to find it.

### Does this app work on ARM?

I don't know

**Comment by QuintenQVD0** [comment]
Duplicate #47
