### ISSUE TITLE
[Bug]: Server not stopping after request to stop

### ISSUE THREAD

**Issue by Notacod3r** [QuintenQVD0/Q_eggs#62]
### Panel Version

1.11.3

### Wings Version

1.11.3

### Service

Vanilla Bedrock ARM64

### Modified

No, I did not modify the egg

### Expected Behavior

The server should stop when the action is requested in the Panel.

### Actual Behavior

After updating to the latest Bedrock Server (1.20.32.03), the server no longer stops when requested, only way to stop it is kill it. And reinstalling the server from scratch does not solve it either. 

Question is, is this a bug with the server version, or the egg?

<img width="739" alt="SCR-20231008-ivgx" src="https://github.com/QuintenQVD0/Q_eggs/assets/98660268/280e0e03-9b80-4558-a038-aaa5d50f47a4">

### Steps To Reproduce

Request to stop. See it being stuck on stopping server

### Install logs

Was not able to do this.

**Comment by QuintenQVD0** [comment]
This is an issue with pterodactyl stop login been broken and the emulator

**Comment by QuintenQVD0** [comment]
I have pushed a trick to the docker image, please wait until it is build and then try again

**Comment by QuintenQVD0** [comment]
else we will have to change the stop command from `stop` to `^C`

**Comment by Notacod3r** [comment]
Thank you Quinten. But what does wait until it is build mean? Sorry I'm not savvy in this area. 

Much appreciated,
Notacod3r

**Comment by QuintenQVD0** [comment]
> Thank you Quinten. But what does wait until it is build mean? Sorry I'm not savvy in this area.
> 
> Much appreciated, Notacod3r

Until the docker image is rebuild. I made some changes to it.

**Comment by Notacod3r** [comment]
Cool! Does the rebuild happen daily or weekly? Like will there be an indication on my panel when I receive the rebuild?

**Comment by QuintenQVD0** [comment]
> > Thank you Quinten. But what does wait until it is build mean? Sorry I'm not savvy in this area.
> > Much appreciated, Notacod3r
> 
> Until the docker image is rebuild. I made some changes to it.

Go to the admin side, nests , the bedrock arm64 egg, change the stop from `stop` to `^C` then it will work

**Comment by QuintenQVD0** [comment]
> Cool! Does the rebuild happen daily or weekly? Like will there be an indication on my panel when I receive the rebuild?

all images auto rebuild every monday. so you will see them pull

**Comment by Notacod3r** [comment]
Super! Really appreciate it Quinten.

**Comment by Notacod3r** [comment]
I received the docker rebuild today, but the issue still existed unfortunately. Stuck on stopping server. I ended up changing stop to ^C in the egg, but this too had no effect.

**Comment by QuintenQVD0** [comment]
> I received the docker rebuild today, but the issue still existed unfortunately. Stuck on stopping server. I ended up changing stop to ^C in the egg, but this too had no effect.

I tryed it yesterday. With ^c it worked just fine

**Comment by Notacod3r** [comment]
Hmm, 
<img width="1142" alt="image" src="https://github.com/QuintenQVD0/Q_eggs/assets/98660268/adbef3c3-afeb-418e-bde1-fb392e12fd02">

For me, I even tried reinstalling the entire server. But still I get stuck on the yellow light.

**Comment by QuintenQVD0** [comment]
> Hmm, <img alt="image" width="1142" src="https://user-images.githubusercontent.com/98660268/273697479-adbef3c3-afeb-418e-bde1-fb392e12fd02.png">
> 
> For me, I even tried reinstalling the entire server. But still I get stuck on the yellow light.

Please update your egg from here, change the stop cmd to ^c and send a screen of where you did that change.

**Comment by Notacod3r** [comment]
<img width="1105" alt="image" src="https://github.com/QuintenQVD0/Q_eggs/assets/98660268/2523ef91-80c2-438e-b014-7ddd5003e8c5">

I updated the egg in the admin settings -> Nests -> Vanilla Bedrock ARM64. And saved it at the bottom.

**Comment by Notacod3r** [comment]
Any Idea if I'm doing it incorrectly?

**Comment by QuintenQVD0** [comment]
> Any Idea if I'm doing it incorrectly?

Seems fine. Ir worked for me.
