### ISSUE TITLE
[Egg Request]: CS2

### ISSUE THREAD

**Issue by giou** [QuintenQVD0/Q_eggs#66]
### Does this expand an already existing service

Yes

### Link to a game or software

https://store.steampowered.com/app/730/CounterStrike_2/

### Links for the download

https://store.steampowered.com/app/730/CounterStrike_2/

### Links for the install docs

https://github.com/1zc/CS2-Pterodactyl

### Does this app work on ARM?

I don't know

**Comment by QuintenQVD0** [comment]
Yea no. It needs a sniper runtime what is amd64 only. And we will not run the client version.
