### ISSUE TITLE
[Egg Request]: Factorio

### ISSUE THREAD

**Issue by SpencerLommel** [QuintenQVD0/Q_eggs#69]
### Does this expand an already existing service

Yes

### Link to a game or software

https://www.factorio.com/

### Links for the download

https://www.factorio.com/download

### Links for the install docs

https://wiki.factorio.com/Multiplayer#Setting_Up_a_Multiplayer_Game

### Does this app work on ARM?

I don't know

**Comment by QuintenQVD0** [comment]
I have made one. It is in the PR if the offical egg repo. I can add it here.
