### ISSUE TITLE
[Egg Request]: Space Engineers

### ISSUE THREAD

**Issue by MellowB1** [QuintenQVD0/Q_eggs#76]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/244850/Space_Engineers/

### Links for the download

https://store.steampowered.com/app/244850/Space_Engineers/

### Links for the install docs

https://gist.github.com/CoffeePirate/102e789310719cad6457

### Does this app work on ARM?

I don't know

**Comment by QuintenQVD0** [comment]
Wine is not possible to emulate.

**Comment by MellowB1** [comment]
thanks for answering so quickly, but now I'm sad.
