### ISSUE TITLE
[Feature Request]: Sharing FEX RootFS between servers

### ISSUE THREAD

**Issue by r3ps4J** [QuintenQVD0/Q_eggs#79]
Right now the FEX RootFS gets downloaded for each server. This makes your disk space fill up quickly since it uses 9GB each time. I was wondering if we could configure this using the mounts feature from Pterodactyl, it seems like a perfect use case for this since the RootFS itself does not (or should not) change.

My idea is the following:
1. Create folder on the root system. (I use `/var/lib/pterodactyl/mounts/fex` but this could be anything)
2. Create the mount in your Pterodactyl panel.
3. Apply the mount for each server that you want to use the shared FEX folder for.
4. Change a startup variable or something to the mounted fex folder so that `/home/container` gets remapped to the mounted location for all FEX folders. (For this I use `/fex` to follow the Pterodactyl docs as closely as possible)

This would also allow you to use different FEX folders for different eggs. Say the FiveM egg uses Ubuntu 20.04 but Satisfactory uses 22.04. You could then make 2 mounts, 1 for 20.04 and 1 for 22.04, and assign the correct mount to each egg.

For the default behaviour you could set the default value of the variable to `/home/container` for the eggs and let server administrators change this value themselves. This would also help prevent issues with people updating their eggs as they will have their RootFS in this directory.

Paths to change to the startup variable in entrypoint.sh from the FEX yolk using `FEX_HOME` as example for the variable (syntax is probably not correct, but you get the idea):
- `if [ -d "/home/container/rootfs" ]` -> `if [ -d "$FEX_HOME/rootfs" ]`
- `if [ -f "/home/container/Config.json" ]; then` -> `if [ -f "$FEX_HOME/Config.json" ]; then`
- `FEX_APP_DATA_LOCATION=/home/container/rootfs` -> `FEX_APP_DATA_LOCATION=$FEX_HOME/rootfs`
- `FEX_APP_CONFIG_LOCATION=/home/container` -> `FEX_APP_CONFIG_LOCATION=$FEX_HOME`
- `XDG_DATA_HOME=/home/container` -> `XDG_DATA_HOME=$FEX_HOME`

I've also included the `Config.json` in this as it seems to only contain the distribution that was used. Didn't think this was something that regular users need to change (and probably shouldn't touch at all). The idea is that the first server that needs FEX creates the RootFS and config files in the /fex mount, which the other servers can then reuse.

I've tried to get this working myself by forking your yolks and changing the eggs to use the same locations, haven't done the actual configuration yet. I got as far as having the RootFS mounted on /fex with the config files, but then got stuck on this error when starting the container:
```
[ERROR] Couldn't connect to FEXServer socket 988.FEXServer.Socket 111 Connection refused
```
Figured you would have a lot more knowledge about docker and pterodactyl, hence why I'm creating this issue.

Info on mounts using Pterodactyl: https://pterodactyl.io/guides/mounts.html

**Comment by QuintenQVD0** [comment]
Hello and thank you for your request. I have already thought about this myself and would certainly like to try to implement it. The big problem is that most users have never set up mounts before. I am currently studying because I have exams throughout the month of January. After that I will have time to try to implement this.

**Comment by QuintenQVD0** [comment]
Did you get a rootfs to download to that directory?

**Comment by r3ps4J** [comment]
All good!

Yeah I got it to download to the mount, but you need to make sure that the mounted folder is owned by the container user (988 for me). The problem I had with that is that I don't have the container user on my host system, so I just set it to 988:988 with chown. It might be easier if the container uses the root user.

**Comment by QuintenQVD0** [comment]
> All good!
> 
> Yeah I got it to download to the mount, but you need to make sure that the mounted folder is owned by the container user (988 for me). The problem I had with that is that I don't have the container user on my host system, so I just set it to 988:988 with chown. It might be easier if the container uses the root user.

Thats not possible. But i see when I have time.

**Comment by r3ps4J** [comment]
Would it work if you include the RootFS in the image? Idk if docker duplicates the image for each container it starts and thus uses that storage multiple times or only use the image space once. I saw this being done here: https://github.com/nitrog0d/palworld-arm64

**Comment by QuintenQVD0** [comment]
I only changed the FEX_APP_DATA_LOCATION as that is were the rootfs will be stored

everything else is about the main dir and the Config.json file (what still should stay in /home/container)
Normaly if you add a variable to the egg called `FEX_ROOTFS_PATH` and change it (default is /home/container/rootfs/`  then fex should put the rootfs there and allow it to be shared over mounts)
