### ISSUE TITLE
[Bug]: BeamMP Egg Fails to Create Server

### ISSUE THREAD

**Issue by FloofyCandy** [QuintenQVD0/Q_eggs#8]
### Panel Version

1.9.2

### Wings Version

1.6.4

### Service

beamng.drive/beammp

### Modified

No, I did not modify the egg

### Expected Behavior

 To properly install the server. (It was working yesterday, I'm not sure what changed)

### Actual Behavior

Failed when "Scanning dependencies of target BeamMP-Server" at 73%

Error:

[ 73%] Building CXX object CMakeFiles/BeamMP-Server.dir/src/main.cpp.o
In file included from /mnt/server/BeamMP-Server/deps/sol2/include/sol/state.hpp:27,
                 from /mnt/server/BeamMP-Server/deps/sol2/include/sol/sol.hpp:57,
                 from /mnt/server/BeamMP-Server/include/TLuaEngine.h:19,
                 from /mnt/server/BeamMP-Server/include/LuaAPI.h:3,
                 from /mnt/server/BeamMP-Server/src/main.cpp:7:
/mnt/server/BeamMP-Server/deps/sol2/include/sol/state_view.hpp: In member function 'sol::gc_mode sol::state_view::change_gc_mode_generational(int, int)':
/mnt/server/BeamMP-Server/deps/sol2/include/sol/state_view.hpp:712:43: warning: unused parameter 'minor_multiplier' [-Wunused-parameter]
  712 |   gc_mode change_gc_mode_generational(int minor_multiplier, int major_multiplier) {
      |                                       ~~~~^~~~~~~~~~~~~~~~
/mnt/server/BeamMP-Server/deps/sol2/include/sol/state_view.hpp:712:65: warning: unused parameter 'major_multiplier' [-Wunused-parameter]
  712 |   gc_mode change_gc_mode_generational(int minor_multiplier, int major_multiplier) {
      |                                                             ~~~~^~~~~~~~~~~~~~~~
/mnt/server/BeamMP-Server/src/main.cpp: In function 'int BeamMPServerMain(MainArguments)':
/mnt/server/BeamMP-Server/src/main.cpp:122:54: error: 'class Commandline' has no member named 'enable_write_to_file'
  122 |     bool Success = Application::Console().Internal().enable_write_to_file("Server.log");
      |                                                      ^~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/BeamMP-Server.dir/build.make:82: CMakeFiles/BeamMP-Server.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:220: CMakeFiles/BeamMP-Server.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
mv: cannot stat 'BeamMP-Server': No such file or directory
mv: cannot stat 'BeamMP.bin': No such file or directory
mv: cannot stat 'BeamMP.bin': No such file or directory
chmod: cannot access 'BeamMP-Server': No such file or directory
done

### Steps To Reproduce

Step 1: Set version to latest
Step 2: Create server
Step 3: Watch install logs

### Install logs

https://pteropaste.com/x0b0yu

**Comment by QuintenQVD0** [comment]
I will have a look. I think I saw that the released a new version

**Comment by QuintenQVD0** [comment]
> ### Panel Version
> 
> 1.9.2
> ### Wings Version
> 
> 1.6.4
> ### Service
> 
> beamng.drive/beammp
> ### Modified
> 
> No, I did not modify the egg
> ### Expected Behavior
> 
> To properly install the server. (It was working yesterday, I'm not sure what changed)
> ### Actual Behavior
> 
> Failed when "Scanning dependencies of target BeamMP-Server" at 73%
> 
> Error:
> 
> [ 73%] Building CXX object CMakeFiles/BeamMP-Server.dir/src/main.cpp.o In file included from /mnt/server/BeamMP-Server/deps/sol2/include/sol/state.hpp:27, from /mnt/server/BeamMP-Server/deps/sol2/include/sol/sol.hpp:57, from /mnt/server/BeamMP-Server/include/TLuaEngine.h:19, from /mnt/server/BeamMP-Server/include/LuaAPI.h:3, from /mnt/server/BeamMP-Server/src/main.cpp:7: /mnt/server/BeamMP-Server/deps/sol2/include/sol/state_view.hpp: In member function 'sol::gc_mode sol::state_view::change_gc_mode_generational(int, int)': /mnt/server/BeamMP-Server/deps/sol2/include/sol/state_view.hpp:712:43: warning: unused parameter 'minor_multiplier' [-Wunused-parameter] 712 | gc_mode change_gc_mode_generational(int minor_multiplier, int major_multiplier) { | ~~~~^~~~~~~~~~~~~~~~ /mnt/server/BeamMP-Server/deps/sol2/include/sol/state_view.hpp:712:65: warning: unused parameter 'major_multiplier' [-Wunused-parameter] 712 | gc_mode change_gc_mode_generational(int minor_multiplier, int major_multiplier) { | ~~~~^~~~~~~~~~~~~~~~ /mnt/server/BeamMP-Server/src/main.cpp: In function 'int BeamMPServerMain(MainArguments)': /mnt/server/BeamMP-Server/src/main.cpp:122:54: error: 'class Commandline' has no member named 'enable_write_to_file' 122 | bool Success = Application::Console().Internal().enable_write_to_file("Server.log"); | ^~~~~~~~~~~~~~~~~~~~ make[2]: *** [CMakeFiles/BeamMP-Server.dir/build.make:82: CMakeFiles/BeamMP-Server.dir/src/main.cpp.o] Error 1 make[1]: *** [CMakeFiles/Makefile2:220: CMakeFiles/BeamMP-Server.dir/all] Error 2 make: *** [Makefile:149: all] Error 2 mv: cannot stat 'BeamMP-Server': No such file or directory mv: cannot stat 'BeamMP.bin': No such file or directory mv: cannot stat 'BeamMP.bin': No such file or directory chmod: cannot access 'BeamMP-Server': No such file or directory done
> ### Steps To Reproduce
> 
> Step 1: Set version to latest Step 2: Create server Step 3: Watch install logs
> ### Install logs
> 
> https://pteropaste.com/x0b0yu

hi, Thanks for reporting!
I indeed have the same issue as you with version set to v3.0.1 or v3.0.2. It looks like a programer fault so I made a issue on there github. If there is any news I will let you now!

**Comment by FloofyCandy** [comment]
rip so is there anything we can do? like ask them to keep linux arm64 support or something?

**Comment by QuintenQVD0** [comment]
> rip so is there anything we can do? like ask them to keep linux arm64 support or something?

The offical not even build binarys for arm. Thats what the egg did but the changed some things and now it does not work anymore

**Comment by FloofyCandy** [comment]
> > rip so is there anything we can do? like ask them to keep linux arm64 support or something?
> 
> 
> 
> The offical not even build binarys for arm. Thats what the egg did but the changed some things and now it does not work anymore

Well that sucks, thank you for your help :)

**Comment by QuintenQVD0** [comment]
> > > rip so is there anything we can do? like ask them to keep linux arm64 support or something?
> > 
> > 
> > The offical not even build binarys for arm. Thats what the egg did but the changed some things and now it does not work anymore
> 
> Well that sucks, thank you for your help :)

I currently got it working on v3.0.1 , the egg was update with this commit: https://github.com/QuintenQVD0/Q_eggs/commit/5d255a3067a0c7b3c7592c3200cc4a32985fe6e8

but in /etc/pterodactyl/config.yml the installer_limits: the memory must be at least 2048 and the cpu at least 125

**Comment by QuintenQVD0** [comment]
I made a small update to also support v3.0.2 but that ` in /etc/pterodactyl/config.yml the installer_limits: the memory must be at least 2048 and the cpu at least 125` is still needed https://github.com/QuintenQVD0/Q_eggs/commit/2735f11feead4c650031a72d219923fcde9b2e39
