### ISSUE TITLE
FiveM Updating TXAdmin

### ISSUE THREAD

**Issue by TheBeastGamer35** [QuintenQVD0/Q_eggs#80]
Is it possible to update the TXAdmin panel for the FiveM server?
I tried updating it but i couldn't find the "Server files" folder were the panel is located.

**Comment by TheBeastGamer35** [comment]
When i reinstall will my resources be deleted?

**Comment by QuintenQVD0** [comment]
> When i reinstall will my resources be deleted?

Normally not, but you always hit backup first

**Comment by TheBeastGamer35** [comment]
Got it updatet thanks for the help
