### ISSUE TITLE
[Egg Request]: HLDS

### ISSUE THREAD

**Issue by Asiimovicek** [QuintenQVD0/Q_eggs#86]
### Does this expand an already existing service

Yes

### Link to a game or software

https://store.steampowered.com/app/10/CounterStrike/

### Links for the download

https://store.steampowered.com/app/10/CounterStrike/

### Links for the install docs

https://developer.valvesoftware.com/wiki/Half-Life_Dedicated_Server

### Does this app work on ARM?

No

**Comment by Asiimovicek** [comment]
I have to say, i already try to done that by myself, but there are few problems...
1. HLDS is unstable inside docker with box86 - with sys_ticrate and pingboost 3, it just crash after a while... it is working without those commands but... I gonna be honest, i want maximum performance because of mods

2. AMXX... I already made an post on alliedmodders about this issue, when box86 cannot emulate alot of functions, needed for master branch and Developer branch of AMXX (1.9 and 1.10) https://forums.alliedmods.net/showthread.php?p=2816958#post2816958
AMXX 1.8 is working, but alot of plugins are currently working on 1.9 or 1.10 and even tho, it is again making it even more unstable...

**Comment by QuintenQVD0** [comment]
> ### Does this expand an already existing service
> Yes
> 
> ### Link to a game or software
> https://store.steampowered.com/app/10/CounterStrike/
> 
> ### Links for the download
> https://store.steampowered.com/app/10/CounterStrike/
> 
> ### Links for the install docs
> https://developer.valvesoftware.com/wiki/Half-Life_Dedicated_Server
> 
> ### Does this app work on ARM?
> No

Please link to the offical Pterodactyl egg, I am not going to write an egg with emulation if it does not already the basics are out. As you did not even link to a proper install doc.

**Comment by Asiimovicek** [comment]
There is no official egg for HLDS, the only egg for HLDS is made by community...
https://github.com/Hembi/cs16-pterodactyl-egg

but in nutshell... exept that server install should be done couple times, do to some sort of bug with downloading the HLDS, there is not much a big difference between SRCDS and HLDS

About install doc., there are couple:
https://unixcop.com/how-to-install-counter-strike-1-6-server-on-ubuntu-debian/
https://www.amoradi.org/20210912011151.html

**Comment by QuintenQVD0** [comment]
> There is no official egg for HLDS, the only egg for HLDS is made by community... https://github.com/Hembi/cs16-pterodactyl-egg
> 
> but in nutshell... exept that server install should be done couple times, do to some sort of bug with downloading the HLDS, there is not much a big difference between SRCDS and HLDS
> 
> About install doc., there are couple: https://unixcop.com/how-to-install-counter-strike-1-6-server-on-ubuntu-debian/ https://www.amoradi.org/20210912011151.html

There is a HLDS offical egg. Same for re-hlds

But I try to see what I can do.

**Comment by Asiimovicek** [comment]
Oh... sorry i didnt even noticed in my life, that there is an official one...
My bad...

But thank you, that you might try.
