### ISSUE TITLE
[Egg Request]: Enshrouded

### ISSUE THREAD

**Issue by Weatwagon** [QuintenQVD0/Q_eggs#88]
### Does this expand an already existing service

Yes

### Link to a game or software

https://enshrouded.com/

### Links for the download

https://enshrouded.zendesk.com/hc/en-us/articles/16051370691485-Dedicated-Server-Installation-on-Steam

### Links for the install docs

https://enshrouded.zendesk.com/hc/en-us/articles/16055441447709-Dedicated-Server-Configuration

### Does this app work on ARM?

I don't know

**Comment by Weatwagon** [comment]
@QuintenQVD0, 

can you check my work [gist to dockerfile,entrypoint.sh,egg-enshrouded-a-r-m64.js](https://gist.github.com/Weatwagon/e05ab62ea73e69e787a0243b31223e30)

I attempted to make an Enshrouded server by combing some yolks form your repo. I put together proton and [box86](https://github.com/QuintenQVD0/yolks/tree/master/emulation/emulation)
and [proton](https://github.com/QuintenQVD0/yolks/tree/master/temp/proton).

Can you tell me if I did these correctly or if they are configured bad. 

My testing the server starts up and i'm able to connect to it.

**Comment by QuintenQVD0** [comment]
We can not run proton on arm64

**Comment by QuintenQVD0** [comment]
as wine and all patches are AMD64 only

**Comment by QuintenQVD0** [comment]
But if it works it works, I leave this open and See what I can do / test

**Comment by Weatwagon** [comment]
"can not" or just runs poorly? I have not kicked the tires on it verry much I'll be able to put some hours of game paly into later today.

**Comment by QuintenQVD0** [comment]
> "can not" or just runs poorly? I have not kicked the tires on it verry much I'll be able to put some hours of game paly into later today.

Last time I tested this, it would just hard crash when attempting to start proton, but you claim you got it to works so ofc I test it, Build the image myself and try

**Comment by QuintenQVD0** [comment]
> Off topic but, thanks for figuring out the RCON on PalWorld. I applied your fix to my startup on arm and it works well there too.

I builded my parser aplication in golang so it als has a native build for that. That is also on my todo list :)

**Comment by QuintenQVD0** [comment]
and @Weatwagon Where in your image are you installing box86?

**Comment by Weatwagon** [comment]
I went back and forth testing different yolks from your repo. I guess the one I copied form your emulation folder only had box64 installed. I'm pretty sure I had one that installed both. I can build a new image with both.

**Comment by QuintenQVD0** [comment]
> I went back and forth testing different yolks from your repo. I guess the one I copied form your emulation folder only had box64 installed. I'm pretty sure I had one that installed both. I can build a new image with both.

I am building a test image rn based on the installer image and removing duplicate packages

**Comment by Weatwagon** [comment]
Oh, I have no doubt you'll find a bunch of trash. I'm only being a script kitty smashing things together and seeing what works. brute force ftw. 

The startup console looks like this now 

```
AMD64 Emualtor image
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 PageSize:4096 Running on Neoverse-N1 with 4 Cores
Params database has 55 entries
Box64 with Dynarec v0.2.7 5f57de01 built on Feb  1 2024 06:28:15
/entrypoint.sh: line 6: box86: command not found
```

So I am running on an image without box86 

I'm also getting errors like this

``` 
Error loading needed lib libSDL3.so.0
Warning: Cannot dlopen("libSDL3.so.0"/0x7fff0ea65a5b, 2)
```
even though I copied the files into the /home/container/stamcmd/linxu32 an 64 folders

**Comment by QuintenQVD0** [comment]
> libSDL3

libSDL3 normally can be ignored, it's not needed

**Comment by QuintenQVD0** [comment]
`quintenqvd/pterodactyl_images:proton` has proton, box64 and box86

**Comment by Weatwagon** [comment]
> `quintenqvd/pterodactyl_images:proton` has proton, box64 and box86

I see the update. I'll do a test with your image. Thanks for cleaning up my trash!

**Comment by Weatwagon** [comment]
@QuintenQVD0 
We played a few hours last night and there were no issues that we found while running with box and proton. With two users connected CPU stayed in the 200-270% range and memory usage sub 2 GiB. 

I wanted to test the performance difference with FEX. Here is my [docker setup ](https://gist.github.com/Weatwagon/c2d149783698b323861c9de6eca74c65)
Can you take a look at it if it can be optimized?

startup command changed to: `export HOME=/home/container; FEXInterpreter /usr/local/bin/proton run  ./enshrouded_server.exe` 

Server is up and running on FEX I'll report the performance difference when I get a chance.

**Comment by QuintenQVD0** [comment]
Does fex with proton preform better then box64 and 86?

**Comment by Weatwagon** [comment]
I'm not at home to test at the moment, but the idle CPU is already lower. 
Fex: 70-85%
box: 105-115%

**Comment by Weatwagon** [comment]
I did a quick test, I remoted into my PC at home. 
With one player connected
Fex: 165-185
Box: 195-215

**Comment by QuintenQVD0** [comment]
Yea thats peity clear. We will go with fex :)

**Comment by Weatwagon** [comment]
haha ok, can you do your magic and make my docker file not so ugly :P

**Comment by Weatwagon** [comment]
I can make it a PR to the yolks repo if that is easier
