### ISSUE TITLE
[Egg Request]: American Truck Simulator

### ISSUE THREAD

**Issue by FM10002** [QuintenQVD0/Q_eggs#89]
### Does this expand an already existing service

Yes

### Link to a game or software

https://store.steampowered.com/app/270880/American_Truck_Simulator/

### Links for the download

https://store.steampowered.com/app/270880/American_Truck_Simulator/

### Links for the install docs

https://modding.scssoft.com/wiki/Documentation/Tools/Dedicated_Server

### Does this app work on ARM?

I don't know

**Comment by QuintenQVD0** [comment]
I am sorry to inform you that this can not work

- fex: fails to find the package file even tho they do exitis
- box64/86 stalls on an error
