### ISSUE TITLE
[Egg Request]: Bots on arm

### ISSUE THREAD

**Issue by anondev-sudo** [QuintenQVD0/Q_eggs#9]
### Does this expand an already existing service

No

### Link to a game or software

-

### Links for the download

https://github.com/parkervcp/eggs/tree/master/bots

### Links for the install docs

Make eggs that support also arm for bots - for example red discord bot is not working on arm

### Does this app work on ARM?

I don't know

**Comment by QuintenQVD0** [comment]
I close this as you do not responde anymore, If you need something specific make a new issue
