### ISSUE TITLE
[Egg Request]: Project Zomboid

### ISSUE THREAD

**Issue by alcomium** [QuintenQVD0/Q_eggs#90]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/108600/Project_Zomboid/

### Links for the download

https://store.steampowered.com/app/108600/Project_Zomboid/

### Links for the install docs

https://pzwiki.net/wiki/Dedicated_server

### Does this app work on ARM?

No

**Comment by alcomium** [comment]
I just modified the official egg and it seems to be working fine, but I'm not sure if this egg is running completely smoothly, so I'm asking for confirmation.
[egg-project-zomboid.json](https://github.com/QuintenQVD0/Q_eggs/files/14167441/egg-project-zomboid.json)

**Comment by QuintenQVD0** [comment]
> I just modified the official egg and it seems to be working fine, but I'm not sure if this egg is running completely smoothly, so I'm asking for confirmation. [egg-project-zomboid.json](https://github.com/QuintenQVD0/Q_eggs/files/14167441/egg-project-zomboid.json)

Mine does not go furthur then 
`LOG  : General     , 1707584763331> 2,894,872> LOADING ASSETS: START`

and with the startup there is no way it should be able to work

**Comment by QuintenQVD0** [comment]
I am going to close this as with the current dtatus this is not possible

**Comment by alcomium** [comment]
Sorry for the late reply. I realized I attached an unmodified file with the startup command, I'll fix it and upload it again.
[egg-project-zomboid.json](https://github.com/QuintenQVD0/Q_eggs/files/14381280/egg-project-zomboid.json)
And you need to wait about 1 minute from LOADING ASSETS: START. it takes 3 minutes to get to Server marked as running... in vanilla, it takes about 3 minutes to get the server marked as running. Please double check and let me know if there's anything need to fix.

**Comment by alcomium** [comment]
![스크린샷 2024-02-23 161809](https://github.com/QuintenQVD0/Q_eggs/assets/14901999/ebdc37c1-bac1-4998-9bd0-214c58453390)
It is working fine on Oracle Cloud ARM instances.
