### ISSUE TITLE
[Bug]: Enshrouded marked as FEX, no FEX_ROOTFS_PATH variable

### ISSUE THREAD

**Issue by VegyBS** [QuintenQVD0/Q_eggs#97]
### Panel Version

1.11.5

### Wings Version

1.11.8

### Service

Enshrouded

### Modified

No, I did not modify the egg

### Expected Behavior

A variable to capture FEX_ROOTFS_PATH in server set up

### Actual Behavior

No FEX_ROOTFS_PATH variable in server set up

### Steps To Reproduce

Create new server in panel, select the enshrouded egg

### Install logs

https://pteropaste.com/e1nck4rumf3z

**Comment by QuintenQVD0** [comment]
this is an issue because the variable is not there? if you want you can make it yourself it will still work

**Comment by VegyBS** [comment]
Exactly what I've done, for now I just added it to the start up command but will get a PR raised

**Comment by VegyBS** [comment]
Appreciate your amazing work here. Thank you
